local farm_buildings = {
    ["antelope-enclosure"] = {default_module = "antelope", domain = "animal"},
    ["arqad-hive"] = {default_module = "arqad", domain = "animal"},
    ["arthurian-pen"] = {default_module = "arthurian", domain = "animal"},
    ["auog-paddock"] = {default_module = "auog", domain = "animal"},
    ["cridren-enclosure"] = {default_module = "cridren", domain = "plant"},
    ["dhilmos-pool"] = {default_module = "dhilmos", domain = "animal"},
    ["dingrits-pack"] = {default_module = "dingrits", domain = "animal"},
    ["fish-farm"] = {default_module = "fish", domain = "animal"},
    ["turd-fish-farm"] = {default_module = "fish", domain = "animal"},
    ["kmauts-enclosure"] = {default_module = "kmauts", domain = "animal"},
    ["mukmoux-pasture"] = {default_module = "mukmoux", domain = "animal"},
    ["phadai-enclosure"] = {default_module = "phadai", domain = "animal"},
    ["phagnot-corral"] = {default_module = "phagnot", domain = "animal"},
    ["prandium-lab"] = {default_module = "cottongut-mk01", domain = "animal"},
    ["ez-ranch"] = {default_module = "korlex", domain = "animal"},
    ["rc"] = {default_module = nil, domain = "animal"},
    ["scrondrix-pen"] = {default_module = "scrondrix", domain = "animal"},
    ["simik-den"] = {default_module = "simik", domain = "animal"},
    ["trits-reef"] = {default_module = "trits", domain = "animal"},
    ["ulric-corral"] = {default_module = "ulric", domain = "animal"},
    ["vonix-den"] = {default_module = "vonix", domain = "animal"},
    ["vrauks-paddock"] = {default_module = "vrauks", domain = "animal"},
    ["xenopen"] = {default_module = "xeno", domain = "animal"},
    ["xyhiphoe-pool"] = {default_module = "xyhiphoe", domain = "animal"},
    ["zipir-reef"] = {default_module = "zipir1", domain = "animal"},
    ["cadaveric-arum"] = {default_module = "cadaveric-arum", domain = "plant"},
    ["fwf"] = {default_module = "tree-mk01", domain = "plant"},
    ["grods-swamp"] = {default_module = "grod", domain = "plant"},
    ["guar-gum-plantation"] = {default_module = "guar", domain = "plant"},
    ["kicalk-plantation"] = {default_module = "kicalk", domain = "plant"},
    ["moondrop-greenhouse"] = {default_module = "moondrop", domain = "plant"},
    ["moss-farm"] = {default_module = "moss", domain = "plant"},
    ["ralesia-plantation"] = {default_module = "ralesia", domain = "plant"},
    ["rennea-plantation"] = {default_module = "rennea", domain = "plant"},
    ["sap-extractor"] = {default_module = "sap-tree", domain = "plant"},
    ["seaweed-crop"] = {default_module = "seaweed", domain = "plant"},
    ["sponge-culture"] = {default_module = "sea-sponge", domain = "plant"},
    ["turd-wpu"] = {default_module = "py-sawblade-module-mk01", domain = "plant"},
    ["tuuphra-plantation"] = {default_module = "tuuphra", domain = "plant"},
    ["yotoi-aloe-orchard"] = {default_module = "yotoi", domain = "plant"},
    ["bhoddos-culture"] = {default_module = "bhoddos", domain = "fungi"},
    ["fawogae-plantation"] = {default_module = "fawogae", domain = "fungi"},
    ["navens-culture"] = {default_module = "navens", domain = "fungi"},
    ["yaedols-culture"] = {default_module = "yaedols", domain = "fungi"},
}

return farm_buildings
