require("__stdlib__/stdlib/data/data").Util.create_data_globals()

require("prototypes/item-groups")
require("prototypes/recipe-categories")

--(( Technology ))--
require("prototypes/technologies/xenobiology")
require("prototypes/technologies/mycology")
require("prototypes/technologies/microbiology")
require("prototypes/technologies/botany")
require("prototypes/technologies/biotech")
require("prototypes/technologies/genetics")
require("prototypes/technologies/zoology")
require("prototypes/technologies/land-animals")
require("prototypes/technologies/water-animals")
require("prototypes/technologies/water-invertebrates")
require("prototypes/technologies/water-gmo-animals")
require("prototypes/technologies/organic-breeding")
require("prototypes/technologies/food")
require("prototypes/technologies/ulric")
require("prototypes/technologies/ralesia")
require("prototypes/technologies/mukmoux")
require("prototypes/technologies/tuuphra")

--(( BUILDINGS ))--
require("prototypes/buildings/moss-farm")
require("prototypes/buildings/seaweed-crop-mk01")
require("prototypes/buildings/moss-farm-mk02")
require("prototypes/buildings/spore-collector-mk01")
require("prototypes/buildings/fwf-mk01")
require("prototypes/buildings/micro-mine-mk01")
require("prototypes/buildings/biofactory-mk01")
require("prototypes/buildings/genlab-mk01")
require("prototypes/buildings/incubator-mk01")
require("prototypes/buildings/creature-chamber-mk01")
require("prototypes/buildings/vrauks-paddock-mk01")
require("prototypes/buildings/slaughterhouse-mk01")
require("prototypes/buildings/sponge-culture-mk01")
require("prototypes/buildings/ulric-corral-mk01")
require("prototypes/buildings/ralesia-plantation-mk01")
require("prototypes/buildings/tuuphra-plantation-mk01")
require("prototypes/buildings/mukmoux-pasture-mk01")
require("prototypes/buildings/data-array")

--(( RECIPES ))--
require('prototypes/items/items')
require('prototypes/recipes/recipes')
require('prototypes/recipes/recipes-mo')
require('prototypes/recipes/recipes-crops')
require('prototypes/recipes/recipes-seaweed')
require('prototypes/recipes/recipes-animals')
require('prototypes/recipes/recipes-ulric')
require('prototypes/recipes/recipes-sea-sponge')
require('prototypes/recipes/recipes-ralesia')
require('prototypes/recipes/recipes-mukmoux')
require('prototypes/recipes/recipes-tuuphra')


--(( FLUIDs ))--
require("prototypes/fluids/zogna-bacteria")
require("prototypes/fluids/blood")
require("prototypes/fluids/formamide")
require("prototypes/fluids/fetal-serum")