--module bonus formula = crafting speed * ( 1 + ( module bounus in decimal * number of modules )
--i.e. 0.01 * ( 1 + ( 15 * 6 )
--module bonus is a whole number do to the size of the bonus amount

require("__stdlib__/stdlib/data/data").Util.create_data_globals()

require("prototypes/item-groups")
require("prototypes/recipe-categories")
require("prototypes/fuel-categories")

--(( Technology ))--
require("prototypes/technologies/xenobiology")
require("prototypes/technologies/kmauts")
require("prototypes/technologies/mycology")
require("prototypes/technologies/microbiology")
require("prototypes/technologies/botany")
require("prototypes/technologies/biotech")
require("prototypes/technologies/genetics")
require("prototypes/technologies/zoology")
require("prototypes/technologies/land-animals")
require("prototypes/technologies/water-animals")
require("prototypes/technologies/water-invertebrates")
require("prototypes/technologies/organic-breeding")
require("prototypes/technologies/molecular-decohesion")
require("prototypes/technologies/food")
require("prototypes/technologies/ulric")
require("prototypes/technologies/ralesia")
require("prototypes/technologies/mukmoux")
require("prototypes/technologies/tuuphra")
require("prototypes/technologies/arthurian")
require("prototypes/technologies/navens")
require("prototypes/technologies/yotoi")
require("prototypes/technologies/xeno")
require("prototypes/technologies/genetic-design")
require("prototypes/technologies/dhilmos")
require("prototypes/technologies/assisted-embryology")
require("prototypes/technologies/scrondrix")
require("prototypes/technologies/pharmagenomics")
require("prototypes/technologies/growth-hormone")
require("prototypes/technologies/anabolic-rna")
require("prototypes/technologies/antiviral")
require("prototypes/technologies/rennea")
require("prototypes/technologies/phadai")
require("prototypes/technologies/auog")
require("prototypes/technologies/yaedols")
require("prototypes/technologies/dingrits")
require("prototypes/technologies/vonix")
require("prototypes/technologies/grod")
require("prototypes/technologies/phagnot")
require("prototypes/technologies/bhoddos")
require("prototypes/technologies/immunosupressants")
require("prototypes/technologies/bio-implants")
require("prototypes/technologies/nanochondria")
require("prototypes/technologies/rendering")
require("prototypes/technologies/advanced-rendering")
require("prototypes/technologies/bmp")
require("prototypes/technologies/pheromones")
require("prototypes/technologies/cridren")
require("prototypes/technologies/domestication")
require("prototypes/technologies/bigger-colon")
require("prototypes/technologies/explosive-diarrhea")
require("prototypes/technologies/zipir")
require("prototypes/technologies/fawogae")
require("prototypes/technologies/antitumor")
require("prototypes/technologies/trits")
require('prototypes/technologies/korlex')
require('prototypes/technologies/recombinant-ery')
require('prototypes/technologies/reca')
require('prototypes/technologies/orexigenic')
require('prototypes/technologies/mega-farm')
require('prototypes/technologies/vrauks')
require('prototypes/technologies/energy-drink')
require('prototypes/technologies/interactive-cognition')
require('prototypes/technologies/exercises')
require('prototypes/technologies/osteocyte')
require('prototypes/technologies/organ-replication')
require('prototypes/technologies/somatic')
require('prototypes/technologies/collagen')
require('prototypes/technologies/force-feeding')
require('prototypes/technologies/bladder')
require('prototypes/technologies/chitin')
require('prototypes/technologies/formic')
require('prototypes/technologies/party-animal')
require('prototypes/technologies/exo-insertion')
require('prototypes/technologies/argumented-spikes')
require('prototypes/technologies/conarium-stem')
require('prototypes/technologies/hydrolase-amplification')
require('prototypes/technologies/zootoxins')
require('prototypes/technologies/artificial-calcification')
require('prototypes/technologies/stochastic-cortex')
require('prototypes/technologies/phytomining')
require('prototypes/technologies/microfilters')
require('prototypes/technologies/organ-printing')
require('prototypes/technologies/biopolymer-clusters')
require('prototypes/technologies/ctc')
require('prototypes/technologies/cottongut')
require('prototypes/technologies/compost')
require('prototypes/technologies/arqad')
require('prototypes/technologies/cardial-hypopharynx')
require('prototypes/technologies/chromasome-infocrystalization')
require('prototypes/technologies/pheromone-transition')
require('prototypes/technologies/laika')

--(( BUILDINGS ))--
require("prototypes/buildings/moss-farm")
require("prototypes/buildings/moss-farm-mk02")
require("prototypes/buildings/moss-farm-mk03")
require("prototypes/buildings/moss-farm-mk04")
require("prototypes/buildings/seaweed-crop-mk01")
require("prototypes/buildings/seaweed-crop-mk02")
require("prototypes/buildings/seaweed-crop-mk03")
require("prototypes/buildings/seaweed-crop-mk04")
require("prototypes/buildings/spore-collector-mk01")
require("prototypes/buildings/spore-collector-mk02")
require("prototypes/buildings/spore-collector-mk03")
require("prototypes/buildings/spore-collector-mk04")
require("prototypes/buildings/fwf-mk01")
require("prototypes/buildings/fwf-mk02")
require("prototypes/buildings/fwf-mk03")
require("prototypes/buildings/fwf-mk04")
require("prototypes/buildings/micro-mine-mk01")
require("prototypes/buildings/micro-mine-mk02")
require("prototypes/buildings/micro-mine-mk03")
require("prototypes/buildings/micro-mine-mk04")
require("prototypes/buildings/biofactory-mk01")
require("prototypes/buildings/biofactory-mk02")
require("prototypes/buildings/biofactory-mk03")
require("prototypes/buildings/biofactory-mk04")
require("prototypes/buildings/genlab-mk01")
require("prototypes/buildings/genlab-mk02")
require("prototypes/buildings/genlab-mk03")
require("prototypes/buildings/genlab-mk04")
require("prototypes/buildings/incubator-mk01")
require("prototypes/buildings/incubator-mk02")
require("prototypes/buildings/incubator-mk03")
require("prototypes/buildings/incubator-mk04")
require("prototypes/buildings/creature-chamber-mk01")
require("prototypes/buildings/creature-chamber-mk02")
require("prototypes/buildings/creature-chamber-mk03")
require("prototypes/buildings/creature-chamber-mk04")
require("prototypes/buildings/vrauks-paddock-mk01")
require("prototypes/buildings/vrauks-paddock-mk02")
require("prototypes/buildings/vrauks-paddock-mk03")
require("prototypes/buildings/vrauks-paddock-mk04")
require("prototypes/buildings/slaughterhouse-mk01")
require("prototypes/buildings/slaughterhouse-mk02")
require("prototypes/buildings/slaughterhouse-mk03")
require("prototypes/buildings/slaughterhouse-mk04")
require("prototypes/buildings/sponge-culture-mk01")
require("prototypes/buildings/sponge-culture-mk02")
require("prototypes/buildings/sponge-culture-mk03")
require("prototypes/buildings/sponge-culture-mk04")
require("prototypes/buildings/ulric-corral-mk01")
require("prototypes/buildings/ulric-corral-mk02")
require("prototypes/buildings/ulric-corral-mk03")
require("prototypes/buildings/ulric-corral-mk04")
require("prototypes/buildings/ralesia-plantation-mk01")
require("prototypes/buildings/ralesia-plantation-mk02")
require("prototypes/buildings/ralesia-plantation-mk03")
require("prototypes/buildings/ralesia-plantation-mk04")
require("prototypes/buildings/tuuphra-plantation-mk01")
require("prototypes/buildings/tuuphra-plantation-mk02")
require("prototypes/buildings/tuuphra-plantation-mk03")
require("prototypes/buildings/tuuphra-plantation-mk04")
require("prototypes/buildings/mukmoux-pasture-mk01")
require("prototypes/buildings/mukmoux-pasture-mk02")
require("prototypes/buildings/mukmoux-pasture-mk03")
require("prototypes/buildings/mukmoux-pasture-mk04")
require("prototypes/buildings/arthurian-pen-mk01")
require("prototypes/buildings/arthurian-pen-mk02")
require("prototypes/buildings/arthurian-pen-mk03")
require("prototypes/buildings/arthurian-pen-mk04")
require("prototypes/buildings/data-array")
require("prototypes/buildings/navens-culture-mk01")
require("prototypes/buildings/navens-culture-mk02")
require("prototypes/buildings/navens-culture-mk03")
require("prototypes/buildings/navens-culture-mk04")
require("prototypes/buildings/yotoi-aloe-orchard-mk01")
require("prototypes/buildings/yotoi-aloe-orchard-mk02")
require("prototypes/buildings/yotoi-aloe-orchard-mk03")
require("prototypes/buildings/yotoi-aloe-orchard-mk04")
require("prototypes/buildings/dhilmos-pool-mk01")
require("prototypes/buildings/dhilmos-pool-mk02")
require("prototypes/buildings/dhilmos-pool-mk03")
require("prototypes/buildings/dhilmos-pool-mk04")
require("prototypes/buildings/scrondrix-pen-mk01")
require("prototypes/buildings/scrondrix-pen-mk02")
require("prototypes/buildings/scrondrix-pen-mk03")
require("prototypes/buildings/scrondrix-pen-mk04")
require("prototypes/buildings/rennea-plantation-mk01")
require("prototypes/buildings/rennea-plantation-mk02")
require("prototypes/buildings/rennea-plantation-mk03")
require("prototypes/buildings/rennea-plantation-mk04")
require("prototypes/buildings/phadai-enclosure-mk01")
require("prototypes/buildings/phadai-enclosure-mk02")
require("prototypes/buildings/phadai-enclosure-mk03")
require("prototypes/buildings/phadai-enclosure-mk04")
require("prototypes/buildings/auog-paddock-mk01")
require("prototypes/buildings/auog-paddock-mk02")
require("prototypes/buildings/auog-paddock-mk03")
require("prototypes/buildings/auog-paddock-mk04")
require("prototypes/buildings/atomizer-mk01")
require("prototypes/buildings/atomizer-mk02")
require("prototypes/buildings/atomizer-mk03")
require("prototypes/buildings/atomizer-mk04")
require("prototypes/buildings/fish-farm-mk01")
require("prototypes/buildings/fish-farm-mk02")
require("prototypes/buildings/fish-farm-mk03")
require("prototypes/buildings/fish-farm-mk04")
require("prototypes/buildings/yaedols-culture-mk01")
require("prototypes/buildings/yaedols-culture-mk02")
require("prototypes/buildings/yaedols-culture-mk03")
require("prototypes/buildings/yaedols-culture-mk04")
require("prototypes/buildings/dingrits-pack-mk01")
require("prototypes/buildings/dingrits-pack-mk02")
require("prototypes/buildings/dingrits-pack-mk03")
require("prototypes/buildings/dingrits-pack-mk04")
require("prototypes/buildings/kmauts-enclosure-mk01")
require("prototypes/buildings/kmauts-enclosure-mk02")
require("prototypes/buildings/kmauts-enclosure-mk03")
require("prototypes/buildings/kmauts-enclosure-mk04")
require("prototypes/buildings/vonix-den-mk01")
require("prototypes/buildings/vonix-den-mk02")
require("prototypes/buildings/vonix-den-mk03")
require("prototypes/buildings/grod-swamp-mk01")
require("prototypes/buildings/grod-swamp-mk02")
require("prototypes/buildings/grod-swamp-mk03")
require("prototypes/buildings/grod-swamp-mk04")
require("prototypes/buildings/phagnot-corral-mk01")
require("prototypes/buildings/phagnot-corral-mk02")
require("prototypes/buildings/phagnot-corral-mk03")
require("prototypes/buildings/phagnot-corral-mk04")
require("prototypes/buildings/bhoddos-culture-mk01")
require("prototypes/buildings/bhoddos-culture-mk02")
require("prototypes/buildings/bhoddos-culture-mk03")
require("prototypes/buildings/bhoddos-culture-mk04")
require("prototypes/buildings/xenopen-mk01")
require("prototypes/buildings/xenopen-mk02")
require("prototypes/buildings/xenopen-mk03")
require("prototypes/buildings/xenopen-mk04")
require("prototypes/buildings/bioreactor-mk01")
require("prototypes/buildings/bioreactor-mk02")
require("prototypes/buildings/bioreactor-mk03")
require("prototypes/buildings/bioreactor-mk04")
require("prototypes/buildings/cridren-enclosure-mk01")
require("prototypes/buildings/cridren-enclosure-mk02")
require("prototypes/buildings/cridren-enclosure-mk03")
require("prototypes/buildings/cridren-enclosure-mk04")
require("prototypes/buildings/zipir-reef-mk01")
require("prototypes/buildings/zipir-reef-mk02")
require("prototypes/buildings/zipir-reef-mk03")
require("prototypes/buildings/zipir-reef-mk04")
require("prototypes/buildings/fawogae-plantation-mk01")
require("prototypes/buildings/sap-extractor-mk01")
require("prototypes/buildings/sap-extractor-mk02")
require("prototypes/buildings/sap-extractor-mk03")
require("prototypes/buildings/sap-extractor-mk04")
require("prototypes/buildings/xyhiphoe-pool-mk01")
require("prototypes/buildings/xyhiphoe-pool-mk02")
require("prototypes/buildings/xyhiphoe-pool-mk03")
require("prototypes/buildings/xyhiphoe-pool-mk04")
require("prototypes/buildings/trits-reef-mk01")
require("prototypes/buildings/trits-reef-mk02")
require("prototypes/buildings/trits-reef-mk03")
require("prototypes/buildings/trits-reef-mk04")
require("prototypes/buildings/bio-printer-mk01")
require("prototypes/buildings/bio-printer-mk02")
require("prototypes/buildings/bio-printer-mk03")
require("prototypes/buildings/bio-printer-mk04")
require("prototypes/buildings/ez-ranch-mk01")
require("prototypes/buildings/ez-ranch-mk02")
require("prototypes/buildings/ez-ranch-mk03")
require("prototypes/buildings/ez-ranch-mk04")
require('prototypes/buildings/generator-1')
require('prototypes/buildings/generator-2')
require('prototypes/buildings/pyphoon-bay')
require('prototypes/buildings/mega-farm')
require('prototypes/buildings/vat-brain')
require("prototypes/buildings/harvester")
require("prototypes/buildings/collector")
require("prototypes/buildings/ipod")
require('prototypes/buildings/prandium-lab-mk01')
require('prototypes/buildings/prandium-lab-mk02')
require('prototypes/buildings/prandium-lab-mk03')
require('prototypes/buildings/prandium-lab-mk04')
require('prototypes/buildings/research-center-mk01')
require('prototypes/buildings/research-center-mk02')
require('prototypes/buildings/research-center-mk03')
require('prototypes/buildings/research-center-mk04')
require('prototypes/buildings/compost-plant-mk01')
require('prototypes/buildings/compost-plant-mk02')
require('prototypes/buildings/compost-plant-mk03')
require('prototypes/buildings/compost-plant-mk04')
require('prototypes/buildings/arqad-hive-mk01')
require('prototypes/buildings/arqad-hive-mk02')
require('prototypes/buildings/arqad-hive-mk03')
require('prototypes/buildings/arqad-hive-mk04')

require('prototypes/buildings/py-drive')

require('prototypes/buildings/outpost')
--require('prototypes/buildings/outpost-mining')
--require('prototypes/buildings/flyavan-outpost')
--weapons/defenses
--require('prototypes/weapons/turrets/gun-turret-mk01')
--require('prototypes/weapons/turrets/rocket-turret-mk01')
--require('prototypes/weapons/landmines/basic-tar-mine')

--ammo
--require('prototypes/weapons/ammo/basic-ammo')
--require('prototypes/weapons/ammo/basic-rocket')

--Creature
require('prototypes/creatures/caravan')
require('prototypes/creatures/nuka-caravan')
--require('prototypes/creatures/flying-caravan')
require('prototypes/creatures/dingrido')
require('prototypes/creatures/crawdad')
require('prototypes/creatures/phadaisus')
require('prototypes/creatures/ocula')
--require('prototypes/creatures/clone-1')
--require('prototypes/creatures/dig-osaurus')

--(( FLUIDS ))--
require("prototypes/fluids/zogna-bacteria")
require("prototypes/fluids/blood")
require("prototypes/fluids/syrup-01")
require("prototypes/fluids/a-molasse")
require("prototypes/fluids/b-molasse")
require("prototypes/fluids/sweet-syrup")
require("prototypes/fluids/ethanol")
require("prototypes/fluids/formamide")
require("prototypes/fluids/fetal-serum")
require("prototypes/fluids/artificial-blood")
require("prototypes/fluids/flutec-pp6")
require("prototypes/fluids/decalin")
require("prototypes/fluids/flavonoids")
require("prototypes/fluids/arthropod-blood")
require("prototypes/fluids/fish-oil")
require("prototypes/fluids/gta")
require("prototypes/fluids/nitrogen-mustard")
require("prototypes/fluids/manure-bacteria")
require("prototypes/fluids/liquid-manure")
require("prototypes/fluids/creamy-latex")
require("prototypes/fluids/formic-acid")
require("prototypes/fluids/subcritical-water")
require("prototypes/fluids/depolymerized-organics")
require("prototypes/fluids/mutant-enzymes")
require("prototypes/fluids/chelator")
require("prototypes/fluids/xenogenic-cells")
require("prototypes/fluids/psc")
require("prototypes/fluids/casein-mixture")
require("prototypes/fluids/casein-pulp-01")
require("prototypes/fluids/casein-pulp-02")
require("prototypes/fluids/casein-solution")
require("prototypes/fluids/milk")
require("prototypes/fluids/autoantigens")
require('prototypes/fluids/cadaveric-arum-cum')
require('prototypes/fluids/wax')
require('prototypes/fluids/arqad-jelly')
require('prototypes/fluids/bee-venom')
require('prototypes/fluids/dda')
require('prototypes/fluids/mcb')
require('prototypes/fluids/chloral')
require('prototypes/fluids/pre-pesticide-01')
require('prototypes/fluids/pre-pesticide-02')
require('prototypes/fluids/ethyl-mercaptan')

--(( RECIPES ))--
require('prototypes/items/items')
require('prototypes/recipes/recipes')
require('prototypes/recipes/recipes-atomizer')
require('prototypes/recipes/recipes-mo')
require('prototypes/recipes/recipes-moss')
require('prototypes/recipes/recipes-moss-products')
require('prototypes/recipes/recipes-seaweed')
require('prototypes/recipes/recipes-seaweed-products')
require('prototypes/recipes/recipes-sap')
require('prototypes/recipes/recipes-sap-products')
require('prototypes/recipes/recipes-animals')
require('prototypes/recipes/recipes-ulric')
require('prototypes/recipes/recipes-sea-sponge')
require('prototypes/recipes/recipes-ralesia')
require('prototypes/recipes/recipes-mukmoux')
require('prototypes/recipes/recipes-tuuphra')
require('prototypes/recipes/recipes-arthurian')
require('prototypes/recipes/recipes-navens')
require('prototypes/recipes/recipes-yotoi')
require('prototypes/recipes/recipes-dhilmos')
require('prototypes/recipes/recipes-scrondrix')
require('prototypes/recipes/recipes-rennea')
require('prototypes/recipes/recipes-phadai')
require('prototypes/recipes/recipes-auog')
require('prototypes/recipes/recipes-fish')
require('prototypes/recipes/recipes-korlex')
require('prototypes/recipes/recipes-yaedols')
require('prototypes/recipes/recipes-auto-ralesia')
require('prototypes/recipes/recipes-auto-fawogae')
require('prototypes/recipes/recipes-auto-navens')
require('prototypes/recipes/recipes-auto-yaedols')
require('prototypes/recipes/recipes-auto-ulric')
require('prototypes/recipes/recipes-auto-vonix')
require('prototypes/recipes/recipes-auto-mukmoux')
require('prototypes/recipes/recipes-auto-bhoddos')
require('prototypes/recipes/recipes-auto-phagnot')
require('prototypes/recipes/recipes-auto-cridren')
require('prototypes/recipes/recipes-auto-grod')
require('prototypes/recipes/recipes-auto-yotoi')
require('prototypes/recipes/recipes-auto-yotoi-fruit')
require('prototypes/recipes/recipes-auto-arthurian')
require('prototypes/recipes/recipes-auto-auog')
require('prototypes/recipes/recipes-auto-dingrits')
require('prototypes/recipes/recipes-auto-kmauts')
require('prototypes/recipes/recipes-auto-korlex')
require('prototypes/recipes/recipes-korlex-products')
require('prototypes/recipes/recipes-korlex-products-2')
require('prototypes/recipes/recipes-auto-dhilmos')
require('prototypes/recipes/recipes-auto-scrondrix')
require('prototypes/recipes/recipes-auto-phadai')
require('prototypes/recipes/recipes-auto-tuuphra')
require('prototypes/recipes/recipes-auto-rennea')
require('prototypes/recipes/recipes-auog-products')
require('prototypes/recipes/recipes-auog-products-2')
require('prototypes/recipes/recipes-auog-products-3')
require('prototypes/recipes/recipes-ulric-products')
require('prototypes/recipes/recipes-ulric-products-2')
require('prototypes/recipes/recipes-ulric-products-3')
require('prototypes/recipes/recipes-mukmoux-products')
require('prototypes/recipes/recipes-mukmoux-products-2')
require('prototypes/recipes/recipes-mukmoux-products-3')
require('prototypes/recipes/recipes-scrondrix-products')
require('prototypes/recipes/recipes-scrondrix-products-2')
require('prototypes/recipes/recipes-scrondrix-products-3')
require('prototypes/recipes/recipes-dingrits')
require('prototypes/recipes/recipes-kmauts')
require('prototypes/recipes/recipes-vonix')
require('prototypes/recipes/recipes-grod')
require('prototypes/recipes/recipes-phagnot')
require('prototypes/recipes/recipes-phagnot-products')
require('prototypes/recipes/recipes-phagnot-products-2')
require('prototypes/recipes/recipes-phagnot-products-3')
require('prototypes/recipes/recipes-bhoddos')
require('prototypes/recipes/recipes-xeno')
require('prototypes/recipes/recipes-cridren')
require('prototypes/recipes/recipes-zipir')
require('prototypes/recipes/recipes-trits')
require('prototypes/recipes/recipes-xyhiphoe')
require('prototypes/recipes/recipes-recharge')
require('prototypes/recipes/recipes-vat')
require('prototypes/recipes/recipes-phadai-products')
require('prototypes/recipes/recipes-ralesia-megafarm')
require('prototypes/recipes/recipes-rennea-megafarm')
require('prototypes/recipes/recipes-tuuphra-megafarm')
require('prototypes/recipes/recipes-grod-megafarm')
require('prototypes/recipes/recipes-yotoi-megafarm')
require('prototypes/recipes/recipes-yotoi-fruit-megafarm')
require('prototypes/recipes/recipes-bioreserve-megafarm')
require('prototypes/recipes/recipes-auto-zipir')
require('prototypes/recipes/recipes-auto-xyhiphoe')
require('prototypes/recipes/recipes-auto-fish')
require('prototypes/recipes/recipes-auto-trits')
require('prototypes/recipes/recipes-auto-xeno')
require('prototypes/recipes/recipes-auto-vrauks')
require('prototypes/recipes/recipes-auto-brains')
require('prototypes/recipes/recipes-auto-brains-2')
require('prototypes/recipes/recipes-auto-meat-1')
require('prototypes/recipes/recipes-auto-meat-2')
require('prototypes/recipes/recipes-auto-bone-1')
require('prototypes/recipes/recipes-auto-bone-2')
require('prototypes/recipes/recipes-auto-guts-1')
require('prototypes/recipes/recipes-auto-guts-2')
require('prototypes/recipes/recipes-auto-blood-1')
require('prototypes/recipes/recipes-auto-blood-2')
require('prototypes/recipes/recipes-auto-skin-1')
require('prototypes/recipes/recipes-auto-skin-2')
require('prototypes/recipes/recipes-auto-fat-1')
require('prototypes/recipes/recipes-auto-fat-2')
require('prototypes/recipes/recipes-bladder')
require('prototypes/recipes/recipes-auto-acessories')
require('prototypes/recipes/recipes-photomining')
require('prototypes/recipes/recipes-bioprinting')
require('prototypes/recipes/recipes-fawogae')
require('prototypes/recipes/recipes-vrauks')
require('prototypes/recipes/recipes-cottongut')
require('prototypes/recipes/recipes-auto-cottongut')
require('prototypes/recipes/recipes-cottongut-science-red')
require('prototypes/recipes/recipes-cottongut-science-green')
require('prototypes/recipes/recipes-cottongut-science-blue')
require('prototypes/recipes/recipes-cottongut-science-py')
require('prototypes/recipes/recipes-arqad')
require('prototypes/recipes/recipes-auto-arqad')
require('prototypes/recipes/recipes-arqad-updates')
require('prototypes/recipes/recipes-arqad-products')
require('prototypes/recipes/recipes-arqad-products-1')
require('prototypes/recipes/recipes-arqad-products-2')
require('prototypes/recipes/recipes-tree')


--gunpowder poo
--require('prototypes/recipes/recipes-vrauk-products')

--(( ORES ))--
require('prototypes/ores/ralesia')
require('prototypes/ores/rennea')
require('prototypes/ores/tuuphra')
require('prototypes/ores/grod')
require('prototypes/ores/yotoi')
require('prototypes/ores/yotoi-fruit')
require('prototypes/ores/bioreserve')

data.raw["utility-constants"].default.recipe_step_limit = 2000;
data.raw["utility-constants"].default.main_menu_background_image_location = "__pyalienlifegraphics3__/graphics/pyal-wall.jpg"

--sprities
require('prototypes/sprites/sprites')
--require('prototypes/ores/fake-plants')

local bio_list = require('prototypes/items/biomass-convertion')

local type

local local_name_type

for i, item in pairs(bio_list) do

--local name = ''
--log(i)
    if item.type == nil or item.type ~= 'fluid' then
        type = 'item'
        local_name_type = 'item'
        --if data.raw.item[i] ~= nil then
           --name = data.raw.item[i].localised_name
        --end
    elseif item.type == 'fluid' then
        type = 'fluid'
        local_name_type = 'fluid'
        --if data.raw.fluid[i] ~= nil then
            --name = data.raw.fluid[i].localised_name
        --end
    end
    --log(serpent.block(data.raw.item[i]))
    local icon
    if type == 'item' and data.raw.item[i] ~= nil then
        if data.raw.item[i].icon ~= nil then
            --log('hit')
            icon = {icon = data.raw.item[i].icon, icon_size = data.raw.item[i].icon_size}
        elseif data.raw.item[i].icons ~= nil then
            --log('hit')
            icon = data.raw.item[i].icons[1]
            if data.raw.item[i].icon_size ~= nil then
                icon.icon_size = data.raw.item[i].icon_size
            elseif data.raw.item[i].icons[1].icon_size ~= nil then
                icon.icon_size = data.raw.item[i].icons[1].icon_size
            end
        end
    elseif type == 'fluid' then
        if data.raw.fluid[i] ~= nil and data.raw.fluid[i].icon ~= nil then
            --log('hit')
            icon = {icon = data.raw.fluid[i].icon, icon_size = data.raw.fluid[i].icon_size}
        elseif data.raw.fluid[i] ~= nil and data.raw.fluid[i].icons ~= nil then
            --log('hit')
            icon = data.raw.fluid[i].icons[1]
        end
    elseif type == 'item' and data.raw.module[i] ~= nil then
        if data.raw.module[i].icon ~= nil then
            --log('hit')
            icon = {icon = data.raw.module[i].icon, icon_size = data.raw.module[i].icon_size}
        elseif data.raw.module[i].icons ~= nil then
            --log('hit')
            if string.match(data.raw.module[i].icons[1].icon, 'over') ~= nil then
                icon = data.raw.module[i].icons[2]
            else
                icon = data.raw.module[i].icons[1]
            end
            if data.raw.module[i].icon_size ~= nil then
                icon.icon_size = data.raw.module[i].icon_size
            elseif data.raw.module[i].icons[1].icon_size ~= nil then
                icon.icon_size = data.raw.module[i].icons[1].icon_size
            end
        end
    end
    if data.raw.item[i] ~= nil or data.raw.fluid[i] ~= nil or data.raw.module[i] ~= nil then
        RECIPE {
            type = 'recipe',
            name = 'biomass-' .. i,
            category = 'compost',
            enabled = false,
			hidden = true,
            energy_required = 3,
            ingredients = {
                {type = type, name = i, amount = item.item_amount},
            },
            results = {
                {type = 'item', name = 'biomass', amount = item.biomass_amount},
            },
            --main_product = 'biomass',
            icons =
                {
                    icon,
                    {icon = "__pyalienlifegraphics__/graphics/icons/biomass.png", scale = 0.50, shift = {-7.5,-7.5}, icon_size = 32}
                },
            subgroup = 'py-alienlife-compost',
            order = i,
            localised_name = {'', 'Compost ' .. item.item_amount .. ' x ', {local_name_type .. '-name.' .. i}}
        }:add_unlock("compost")
        --log(serpent.block(data.raw.recipe['biomass-' .. i]))
    end
end

local fun = require("prototypes/functions/functions")

fun.reprocess_recipes_1()

fun.reprocess_recipes_2()
