local FUN = require("__pycoalprocessing__/prototypes/functions/functions")

--ADAPTATIONS

--RECIPES UPDATES

RECIPE('exoskeleton-equipment'):add_ingredient({type = "item", name = "metallic-glass", amount = 30})
RECIPE('plastic-bar'):remove_unlock('plastics')
RECIPE('automation-science-pack'):change_category('research')
RECIPE('logistic-science-pack'):change_category('research')
RECIPE('chemical-science-pack'):change_category('research')
RECIPE('military-science-pack'):change_category('research')
RECIPE('production-science-pack'):change_category('research'):remove_unlock('diamond-mining'):add_unlock('pharmagenomics')
RECIPE('utility-science-pack'):change_category('research'):add_ingredient({type = "item", name = "perfect-samples", amount = 1})

for _,module in pairs(data.raw.module) do
  if module.subgroup == "py-alienlife-modules" then
    for _, recipe in pairs(data.raw.recipe) do
      if recipe.category == module.category and module.limitation ~= nil and module.limitation[recipe.name] == nil then
        table.insert(module.limitation, recipe.name)
      end
    end
  end
end

log(serpent.block(data.raw.module.gord))

for _, drill in pairs(data.raw['mining-drill']) do
	drill.allowed_effects = {"consumption", "speed", "pollution"}
end

local speed_module_blacklist =
    {
  "sea-sponge-1",
  "sea-sponge-2",
  "ralesias1",
  "ralesias2",
  "ralesias3",
  "ralesias4",
  "ralesias5",
  "ralesias6",
  "ralesias7",
  "ralesias8",
  "ralesias9",
  "ralesias10",
  "ralesias11",
  "ralesias12",
  "ralesias13",
  "ralesias14",
  "kicalk1",
  "kicalk2",
  "kicalk3",
  "kicalk4",
  "kicalk5",
  "kicalk6",
  "kicalk7",
  "kicalk8",
  "kicalk9",
  "kicalk10",
  "kicalk11",
  "kicalk12",
  "kicalk13",
  "kicalk14",
  "tuuphra1",
  "tuuphra2",
  "tuuphra3",
  "tuuphra4",
  "tuuphra5",
  "tuuphra6",
  "tuuphra7",
  "tuuphra8",
  "tuuphra9",
  "tuuphra10",
  "tuuphra11",
  "tuuphra12",
  "tuuphra13",
  "tuuphra14",
  "navens1",
  "navens2",
  "navens3",
  "navens4",
  "navens5",
  "navens6",
  "navens7",
  "navens8",
  "navens9",
  "navens10",
  "navens11",
  "navens12",
  "yotoi1",
  "yotoi2",
  "yotoi3",
  "yotoi4",
  "yotoi5",
  "yotoi6",
  "yotoi7",
  "yotoi8",
  "yotoi9",
  "yotoi10",
  "yotoi11",
  "yotoi12",
  "yotoi13",
  "yotoi14",
  "yotoifruit1",
  "yotoifruit2",
  "yotoifruit3",
  "yotoifruit4",
  "yotoifruit5",
  "yotoifruit6",
  "yotoifruit7",
  "yotoifruit8",
  "yotoifruit9",
  "yotoifruit10",
  "yotoifruit11",
  "yotoifruit12",
  "yotoifruit13",
  "yotoifruit14",
  "rennea1",
  "rennea2",
  "rennea3",
  "rennea4",
  "rennea5",
  "rennea6",
  "rennea7",
  "rennea8",
  "rennea9",
  "rennea10",
  "rennea11",
  "rennea12",
  "rennea13",
  "rennea14",
  "grod1",
  "grod2",
  "grod3",
  "grod4",
  "grod5",
  "grod6",
  "grod7",
  "grod8",
  "grod9",
  "grod10",
  "grod11",
  "grod12",
  "grod13",
  "grod14",
  "grod15",
  "bhoddos1",
  "bhoddos2",
  "bhoddos3",
  "bhoddos4",
  "bhoddos5",
  "bhoddos6",
  "bhoddos7",
  "bhoddos8",
  "bhoddos9",
  "bhoddos10",
  "bhoddos11",
  "bhoddos12",
  "bhoddos13",
  "bhoddos14",
  "cadaveric-arum1",
  "cadaveric-arum2",
  "cadaveric-arum3",
  "cadaveric-arum4",
  "cadaveric-arum5",
  "cadaveric-arum6",
  "cadaveric-arum7",
  "cadaveric-arum8",
  "cadaveric-arum9",
  "cadaveric-arum10",
  "cadaveric-arum11",
  "cadaveric-arum12",
  "cadaveric-arum13"
  }

local function effectivityblacklist(cat)

	local catlist = {}
	local effectlimitaionlist = {}
	local set = {}

	for _, c in pairs(cat) do
		catlist[c] = true
	end

	--convert recipe table into a set
	for _, recipe in pairs(data.raw.recipe) do
		if catlist[data.raw.recipe[recipe.name].category] ~= nil then
			set[recipe.name] = true
		end
	end

	for _,recipe in pairs(data.raw.recipe) do
		if set[recipe.name] == nil then
			table.insert(effectlimitaionlist, recipe.name)
		end
	end
	data.raw.module["speed-module"].limitation = effectlimitaionlist
	data.raw.module["speed-module"].limitation_message_key = 'cant be used here'
	data.raw.module["speed-module-2"].limitation = effectlimitaionlist
	data.raw.module["speed-module-2"].limitation_message_key = 'cant be used here'
	data.raw.module["speed-module-3"].limitation = effectlimitaionlist
	data.raw.module["speed-module-3"].limitation_message_key = 'cant be used here'

end

effectivityblacklist(speed_module_blacklist)
--[[
local shrecipes = {}

for r, recipe in pairs(data.raw.recipe) do
  if recipe.category ~= nil and string.match(recipe.category, 'slaughterhouse') then
    table.insert(shrecipes, recipe.name)
  end
end

log(serpent.block(shrecipes))
]]--

local recipes_list =
	{
	"moss-farm-mk01",
  "moss-farm-mk02",
  "moss-farm-mk03",
  "moss-farm-mk04",
  "seaweed-crop-mk01",
  "seaweed-crop-mk02",
  "seaweed-crop-mk03",
  "seaweed-crop-mk04",
  "spore-collector-mk01",
  "spore-collector-mk02",
  "spore-collector-mk03",
  "spore-collector-mk04",
  "fwf-mk01",
  "fwf-mk02",
  "fwf-mk03",
  "fwf-mk04",
  "micro-mine-mk01",
  "micro-mine-mk02",
  "micro-mine-mk03",
  "micro-mine-mk04",
  "biofactory-mk01",
  "biofactory-mk02",
  "biofactory-mk03",
  "biofactory-mk04",
  "incubator-mk01",
  "incubator-mk02",
  "incubator-mk03",
  "incubator-mk04",
  "creature-chamber-mk01",
  "creature-chamber-mk02",
  "creature-chamber-mk03",
  "creature-chamber-mk04",
  "vrauks-paddock-mk01",
  "vrauks-paddock-mk02",
  "vrauks-paddock-mk03",
  "vrauks-paddock-mk04",
  "slaughterhouse-mk01",
  "slaughterhouse-mk02",
  "slaughterhouse-mk03",
  "slaughterhouse-mk04",
  "sponge-culture-mk01",
  "sponge-culture-mk02",
  "sponge-culture-mk03",
  "sponge-culture-mk04",
  "ulric-corral-mk01",
  "ulric-corral-mk02",
  "ulric-corral-mk03",
  "ulric-corral-mk04",
  "ralesia-plantation-mk01",
  "tuuphra-plantation-mk01",
  "tuuphra-plantation-mk02",
  "tuuphra-plantation-mk03",
  "tuuphra-plantation-mk04",
  "mukmoux-pasture-mk01",
  "mukmoux-pasture-mk02",
  "mukmoux-pasture-mk03",
  "mukmoux-pasture-mk04",
  "arthurian-pen-mk01",
  "arthurian-pen-mk02",
  "arthurian-pen-mk03",
  "arthurian-pen-mk04",
  "data-array",
  "navens-culture-mk01",
  "navens-culture-mk02",
  "navens-culture-mk03",
  "navens-culture-mk04",
  "yotoi-aloe-orchard-mk01",
  "yotoi-aloe-orchard-mk02",
  "yotoi-aloe-orchard-mk03",
  "yotoi-aloe-orchard-mk04",
  "dhilmos-pool-mk01",
  "dhilmos-pool-mk02",
  "dhilmos-pool-mk03",
  "dhilmos-pool-mk04",
  "scrondrix-pen-mk01",
  "scrondrix-pen-mk02",
  "scrondrix-pen-mk03",
  "scrondrix-pen-mk04",
  "rennea-plantation-mk01",
  "rennea-plantation-mk02",
  "rennea-plantation-mk03",
  "rennea-plantation-mk04",
  "phadai-enclosure-mk01",
  "phadai-enclosure-mk02",
  "phadai-enclosure-mk03",
  "phadai-enclosure-mk04",
  "auog-paddock-mk01",
  "auog-paddock-mk02",
  "auog-paddock-mk03",
  "auog-paddock-mk04",
  "atomizer-mk01",
  "atomizer-mk02",
  "atomizer-mk03",
  "atomizer-mk04",
  "fish-farm-mk01",
  "fish-farm-mk02",
  "fish-farm-mk03",
  "fish-farm-mk04",
  "yaedols-culture-mk01",
  "yaedols-culture-mk02",
  "yaedols-culture-mk03",
  "yaedols-culture-mk04",
  "dingrits-pack-mk01",
  "dingrits-pack-mk02",
  "dingrits-pack-mk03",
  "dingrits-pack-mk04",
  "vonix-den-mk01",
  "vonix-den-mk02",
  "vonix-den-mk03",
  "grods-swamp-mk01",
  "grods-swamp-mk02",
  "grods-swamp-mk03",
  "grods-swamp-mk04",
  "phagnot-corral-mk01",
  "phagnot-corral-mk02",
  "phagnot-corral-mk03",
  "phagnot-corral-mk04",
  "bhoddos-culture-mk01",
  "bhoddos-culture-mk02",
  "bhoddos-culture-mk03",
  "bhoddos-culture-mk04",
  "xenopen-mk01",
  "xenopen-mk02",
  "xenopen-mk03",
  "xenopen-mk04",
  "arqad-hive-mk01",
  "arqad-hive-mk02",
  "arqad-hive-mk03",
  "arqad-hive-mk04",
  "bio-reactor-mk01",
  "bio-reactor-mk02",
  "bio-reactor-mk03",
  "bio-reactor-mk04",
  "cridren-enclosure-mk01",
  "cridren-enclosure-mk02",
  "cridren-enclosure-mk03",
  "cridren-enclosure-mk04",
  "zipir-reef-mk01",
  "zipir-reef-mk02",
  "zipir-reef-mk03",
  "zipir-reef-mk04",
  "fawogae-plantation-mk01",
  "sap-extractor-mk01",
  "sap-extractor-mk02",
  "sap-extractor-mk03",
  "sap-extractor-mk04",
  "trits-reef-mk01",
  "trits-reef-mk02",
  "trits-reef-mk03",
  "trits-reef-mk04",
  "outpost",
  "food-bowl",
  "generator-1",
  "generator-2",
  "pyphoon-bay",
  "lb-control-tower",
  "lb-requester-chest",
  "lb-provider-chest",
  "lb-storage-chest",
  "mega-farm",
  "vat-brain",
  "harvester",
  "collector",
  "caravan",
  "land-bot",
  "py-locomotive",
  "zogna-bacteria",
  "formamide",
  "artificial-blood",
  "fish-oil",
  "manure-bacteria",
  "liquid-manure",
  "creamy-latex",
  "formic-acid",
  "biomass-1",
  "biomass-2",
  --"fungal-substrate",
  --"fungal-substrate-02",
  "fungal-substrate-03",
  "wood-seedling",
  "wood-seeds",
  "empty-petri-dish",
  "coke-co2",
  "agar",
  "petri-dish",
  "moss-gen",
  "cage",
  "neuroprocessor",
  "py-science-pack",
  "fertilizer-1",
  "fertilizer-4",
  "flutec-pp6",
  "cobalt-fluoride",
  "decalin",
  "flavonoids",
  "cytostatics",
  "microcin-j25",
  "resveratrol",
  "gh",
  "lard-from-brains",
  "hcl-from-guts",
  "olechemicals-from-skin",
  "pelt-processing",
  "reca",
  "mixed-ores",
  "cobalt-extract",
  "cobalt-sulfate",
  "cobalt-sulfate-02",
  "cobalt-oxide",
  "cobalt-nx",
  "dried-grods",
  --"bedding",
  "zymogens",
  "mmp",
  "peptidase-m58",
  "alien-enzymes",
  "antiviral",
  "nitrogen-mustard",
  "pacifastin",
  "metallic-glass",
  "ticocr-alloy",
  "nanochondria",
  "bmp",
  "hyaline",
  "cellulose-00",
  "cellulose-02",
  "lignin",
  "lignin-to-aromatics",
  "pheromones",
  "neuromorphic-chip",
  "nano-cellulose",
  "gasoline-cellulose",
  "filtration-media-3",
  "cellulose-gasification",
  "yotoi-cellulose",
  "biofilm-3",
  "manure-to-biomass",
  "manure-to-crude",
  "sodium-alginate",
  "latex-slab",
  "latex",
  "stopper",
  "sap-01",
  --"adrenal-cortex",
  "bio-container",
  "naven-coal",
  "oleochemical-combustion",
  "fish-oil-combustion",
  "lard-combustion",
  "ethanol-combustion",
  "seeds-extract-01",
  "syrup-01",
  "energy-drink",
  "a-molasse",
  "sweet-syrup",
  "sugar",
  "b-molasse",
  "ethanol",
  "lime-from-shell",
  "replicator-bioreserve",
  "oleochemicals-3",
  "blood-to-iron",
  "meat-to-iron",
  "meat-and-gut-to-copper",
  "arthropod-blood-to-copper",
  "tuuphra-to-copper",
  "meat-to-copper",
  "guts-to-copper",
  "fish-to-iron",
  "tuupha-to-iron",
  "fawogae-to-iron",
  "fish-to-tin",
  "meat-to-nitrogen",
  "guts-to-chlorine",
  "blood-to-chlorine",
  "brain-guts-to-zinc",
  "grod-to-zinc",
  "blood-to-zinc",
  "bhoddos-to-ti",
  "navens-to-ti",
  "yaedol-to-sulfur",
  "fawogae-to-sulfur",
  "rennea-to-copper",
  "yaedols-to-copper",
  "brain-to-zinc",
  "guts-to-zinc",
  "carapace-to-al",
  "spikes-to-mo",
  "tuuphra-to-mo",
  "cridren-seeds-to-mo",
  "yotoi-leaves-to-chromium",
  "yotoi-fruit-to-chromium",
  "meat-to-chromium",
  "yotoi-seed-to-chromium",
  "meat-to-tin",
  "yotoi-fruit-to-tin",
  "grod-to-tin",
  "navens-to-tin",
  "manure-to-nitrogen",
  "fawogae-spore",
  "petri-dish-bacteria",
  "plasmids",
  "retrovirus",
  "retrovirus-2",
  "cdna",
  "primers",
  "dna-polymerase",
  "dna-polymerase-2",
  "alien-sample-02",
  "alien-sample-03",
  "gta",
  "cysteine",
  "adam42-gen",
  "zinc-finger-proteins",
  "anabolic-rna",
  "propeptides",
  "purine-analogues",
  "immunosupressants",
  "antitumor",
  "dynemicin",
  "enediyne",
  "enzyme-pks",
  "recombinant-ery",
  "recombinant-ery-2",
  "orexigenic",
  "moss-1",
  "moss-2",
  "moss-3",
  "moss-4",
  "phytoplankton-2",
  "seaweed",
  "seaweed-2",
  "seaweed-3",
  "seaweed-4",
  "seaweed-9",
  "seaweed-5",
  "seaweed-6",
  "seaweed-7",
  "fetal-serum-01",
  "vrauks",
  "vrauks-codex",
  "earth-generic-sample",
  "vrauks-food-01",
  "vrauks-food-02",
  "cottongut-food-01",
  "cottongut-food-02",
  "korlex-food-01",
  "korlex-food-02",
  --"caged-vrauks",
  --"uncaged-vrauks",
  "vrauks-mature-01",
  "vrauks-mature-02",
  "vrauks-mk02",
  "vrauks-mk03",
  "vrauks-mk04",
  "ulric",
  "ulric-codex",
  "earth-horse-sample",
  "ulric-food-01",
  "ulric-food-02",
  "ulric-mature-01",
  "ulric-mature-02",
  --"caged-ulric",
  --"uncaged-ulric",
  "ulric-mk02",
  "ulric-mk03",
  "ulric-mk04",
  "sea-sponge",
  "sea-sponge-codex",
  "earth-sea-sponge-sample",
  "sea-sponge-processing-01",
  "sea-sponge-sprouts-processing-01",
  "sea-sponge-sprouts",
  "sea-sponge-sprouts-2",
  "sea-sponge-sprouts-3",
  "sea-sponge-sprouts-4",
  "sea-sponge-mk02",
  "sea-sponge-mk03",
  "sea-sponge-mk04",
  "ralesia-sample",
  "ralesia-codex",
  "earth-flower-sample",
  "replicator-ralesia",
  "ralesias-mk02",
  "ralesias-mk03",
  "ralesias-mk04",
  "mukmoux",
  "mukmoux-codex",
  "earth-cow-sample",
  "mukmoux-food-01",
  "mukmoux-food-02",
  "mukmoux-mature-01",
  "mukmoux-mature-02",
  --"caged-mukmoux",
  --"uncaged-mukmoux",
  "mukmoux-mk02",
  "mukmoux-mk03",
  "mukmoux-mk04",
  "tuuphra-sample",
  "tuuphra-codex",
  "earth-potato-sample",
  "tuuphra-seeds",
  "replicator-tuuphra",
  "tuuphra-mk02",
  "tuuphra-mk03",
  "tuuphra-mk04",
  "arthurian",
  "arthurian-codex",
  "earth-lizard-sample",
  "arthurian-food-01",
  "arthurian-food-02",
  "arthurian-grow-01",
  "arthurian-mature-01",
  "arthurian-mature-02",
  --"caged-arthurian",
  --"uncaged-arthurian",
  "arthurian-mk02",
  "arthurian-mk03",
  "arthurian-mk04",
  "navens-sample",
  "navens-codex",
  "navens-spore",
  "navens-mk02",
  "navens-mk03",
  "navens-mk04",
  "yotoi-sample",
  "yotoi-codex",
  "earth-tropical-tree-sample",
  "yotoi-seeds",
  "yotoi-leaves",
  "replicator-yotoi",
  "replicator-yotoi-fruit",
  "yotoi-mk02",
  "yotoi-mk03",
  "yotoi-mk04",
  "dhilmos",
  "dhilmos-codex",
  "dhilmos-grow-01",
  "dhilmos-mature-01",
  "dhilmos-mature-02",
  "dhilmos-food-01",
  "dhilmos-food-02",
  "dhilmos-mk02",
  "dhilmos-mk03",
  "dhilmos-mk04",
  "scrondrix",
  "scrondrix-codex",
  "earth-roadrunner-sample",
  "scrondrix-mature-01",
  "scrondrix-mature-02",
  --"caged-scrondrix",
  --"uncaged-scrondrix",
  "scrondrix-mk02",
  "scrondrix-mk03",
  "scrondrix-mk04",
  "rennea-sample",
  "rennea-codex",
  "earth-sunflower-sample",
  "rennea-seeds",
  "replicator-rennea",
  "rennea-mk02",
  "rennea-mk03",
  "rennea-mk04",
  "phadai",
  "phadai-codex",
  "earth-tiger-sample",
  "phadai-food-01",
  "phadai-food-02",
  "phadai-mature-01",
  "phadai-mature-02",
  --"caged-phadai",
  --"uncaged-phadai",
  "phadai-mk02",
  "phadai-mk03",
  "phadai-mk04",
  "auog",
  "auog-codex",
  "earth-bear-sample",
  "auog-food-01",
  "auog-food-02",
  "auog-mature-01",
  "auog-mature-02",
  --"caged-auog",
  --"uncaged-auog",
  "charged-auog",
  "auog-mk02",
  "auog-mk03",
  "auog-mk04",
  "fish-food-01",
  "fish-food-02",
  "fish-sex-pup-01",
  "fish-sex-pup-02",
  "fish-mature-01",
  --"fish-full-rendering",
  "yaedols-sample",
  "yaedols-codex",
  "yaedols-spores",
  "yaedols-mk02",
  "yaedols-mk03",
  "yaedols-mk04",
  --"fawogae1",
  --"fawogae3",
  --"fawogae4",
  --"fawogae5",
  --"fawogae6",
  --"fawogae7",
  --"fawogae8",
  --"fawogae9",
  --"fawogae10",
  --"fawogae11",
  --"fawogae12",
  --"fawogae13",
  --"fawogae14",
  --"fawogae15",
  --"caged-ulric1",
  --"caged-ulric2",
  --"caged-ulric3",
  --"caged-ulric4",
  --"caged-ulric5",
  --"caged-ulric6",
  --"caged-ulric7",
  --"caged-ulric8",
  --"caged-ulric9",
  --"caged-ulric10",
  --"caged-ulric11",
  --"caged-ulric12",
  --"caged-ulric13",
  --"caged-ulric14",
  --"caged-ulric15",
  --"caged-ulric16",
  --"caged-ulric17",
  --"caged-ulric18",
  --"caged-ulric19",
  --"caged-ulric20",
  --"caged-ulric21",
  --"caged-ulric22",
  --"caged-ulric23",
  --"caged-ulric24",
  --"ulric-cub1",
  --"ulric-cub2",
  --"ulric-cub3",
  --"ulric-cub4",
  --"ulric-cub5",
  --"ulric-cub6",
  --"ulric-cub7",
  --"ulric-cub8",
  --"ulric-cub9",
  --"ulric-cub10",
  --"ulric-cub11",
  --"ulric-cub12",
  --"ulric-cub13",
  --"ulric-cub14",
  --"full render Ulrics",
  --"Ulrics to Bonemeal",
  --"Extract Ulric Meat",
  --"Extract Ulric brains",
  --"Extract Ulric skin",
  --"Extract Ulric bones",
  --"Extract Ulric guts",
  --"Extract Ulric blood",
  --"Extract Ulric lard",
  --"Extract brains from Improved Ulrics",
  --"Extract bones from Improved Ulrics",
  --"Extract bonemeal from Improved Ulrics",
  --"Extract guts from Improved Ulrics",
  --"Extract blood from Improved Ulrics",
  --"Extract skin from Improved Ulrics",
  --"Extract fat from Improved Ulrics",
  --"Extract meat from Improved Ulrics",
  --"vonix1",
  --"vonix2",
  --"vonix3",
  --"vonix4",
  --"vonix5",
  --"vonix6",
  --"vonix7",
  --"vonix8",
  --"vonix9",
  --"vonix10",
  --"vonix11",
  --"vonix12",
  --"vonix13",
  --"vonix14",
  --"vonix15",
  --"vonix16",
  --"vonix17",
  --"vonix18",
  --"vonix19",
  --"vonix20",
  --"vonix-cub1",
  --"vonix-cub2",
  --"vonix-cub3",
  --"vonix-cub4",
  --"vonix-cub5",
  --"vonix-cub6",
  --"vonix-cub7",
  --"vonix-cub8",
  --"vonix-cub9",
  --"vonix-cub10",
  --"full render Vonix",
  --"Extract Vonix Meat",
  --"Extract Vonix brain",
  --"Extract Vonix´s Venom Gland",
  --"Extract Vonix skin",
  --"Extract Vonix guts",
  --"Extract Vonix blood",
  --"Extract Vonix lard",
  --"Extract brains from Improved Vonixes",
  --"Extract guts from Improved Vonixes",
  --"Extract Arthropod blood from Improved Vonixes",
  --"Extract skin from Improved Vonixes",
  --"Extract fat from Improved Vonixes",
  --"Extract meat from Improved Vonixes",
  --"caged-mukmoux1",
  --"caged-mukmoux2",
  --"caged-mukmoux3",
  --"caged-mukmoux4",
  --"caged-mukmoux5",
  --"caged-mukmoux6",
  --"caged-mukmoux7",
  --"caged-mukmoux8",
  --"caged-mukmoux9",
  --"caged-mukmoux10",
  --"caged-mukmoux11",
  --"caged-mukmoux12",
  --"caged-mukmoux13",
  --"caged-mukmoux14",
  --"caged-mukmoux15",
  --"caged-mukmoux16",
  --"caged-mukmoux17",
  --"caged-mukmoux18",
  --"caged-mukmoux19",
  --"caged-mukmoux20",
  --"caged-mukmoux21",
  --"caged-mukmoux22",
  --"caged-mukmoux23",
  --"caged-mukmoux24",
  --"mukmoux-calf1",
  --"mukmoux-calf2",
  --"mukmoux-calf3",
  --"mukmoux-calf4",
  --"mukmoux-calf5",
  --"mukmoux-calf6",
  --"mukmoux-calf7",
  --"mukmoux-calf8",
  --"mukmoux-calf9",
  --"mukmoux-calf10",
  --"mukmoux-calf11",
  --"mukmoux-calf12",
  --"mukmoux-calf13",
  --"mukmoux-calf14",
  --"full render Mukmouxs",
  --"Mukmouxs to Bonemeal",
  --"Extract Mukmoux Meat",
  --"Extract Mukmoux brains",
  --"Extract Mukmoux skin",
  --"Extract Mukmoux bones",
  --"Extract Mukmoux guts",
  --"Extract Mukmoux blood",
  --"Extract Mukmoux lard",
  --"Extract brains from Improved Mukmouxs",
  --"Extract bones from Improved Mukmouxs",
  --"Extract meat from Improved Mukmouxs",
  --"Extract guts from Improved Mukmouxs",
  --"Extract blood from Improved Mukmouxs",
  --"Extract skin from Improved Mukmouxs",
  --"Extract fat from Improved Mukmouxs",
  --"caged-phagnot1",
  --"caged-phagnot2",
  --"caged-phagnot3",
  --"caged-phagnot4",
  --"caged-phagnot5",
  --"caged-phagnot6",
  --"caged-phagnot7",
  --"caged-phagnot8",
  --"caged-phagnot9",
  --"caged-phagnot10",
  --"caged-phagnot11",
  --"caged-phagnot12",
  --"caged-phagnot13",
  --"caged-phagnot14",
  --"caged-phagnot15",
  --"caged-phagnot16",
  --"caged-phagnot17",
  --"caged-phagnot18",
  --"caged-phagnot19",
  --"caged-phagnot20",
  --"caged-phagnot21",
  --"caged-phagnot22",
  --"phagnot-cub1",
  --"phagnot-cub2",
  --"phagnot-cub3",
  --"phagnot-cub4",
  --"phagnot-cub5",
  --"phagnot-cub6",
  --"phagnot-cub7",
  --"phagnot-cub8",
  --"phagnot-cub9",
  --"phagnot-cub10",
  --"phagnot-cub11",
  --"phagnot-cub12",
  --"phagnot-cub13",
  --"phagnot-cub14",
  --"full render phagnots",
  --"Extract phagnot Meat",
  --"Extract phagnot brains",
  --"Extract phagnot skin",
  --"Extract phagnot bones",
  --"Extract phagnot guts",
  --"Extract phagnot blood",
  --"Extract phagnot Gas bladder",
  --"Extract brains from Improved phagnots",
  --"Extract bones from Improved phagnots",
  --"Extract guts from Improved phagnots",
  --"Extract blood from Improved phagnots",
  --"Extract skin from Improved phagnots",
  --"Extract meat from Improved phagnots",
  --"cridren1",
  --"cridren2",
  --"cridren3",
  --"cridren4",
  --"cridren5",
  --"cridren6",
  --"cridren7",
  --"cridren8",
  --"cridren9",
  --"cridren10",
  --"cridren11",
  --"cridren12",
  --"cridren13",
  --"caged-arthurian1",
  --"caged-arthurian2",
  --"caged-arthurian3",
  --"caged-arthurian4",
  --"caged-arthurian5",
  --"caged-arthurian6",
  --"caged-arthurian7",
  --"caged-arthurian8",
  --"caged-arthurian9",
  --"caged-arthurian10",
  --"caged-arthurian11",
  --"caged-arthurian12",
  --"caged-arthurian13",
  --"caged-arthurian14",
  --"caged-arthurian15",
  --"caged-arthurian16",
  --"caged-arthurian17",
  --"caged-arthurian18",
  --"caged-arthurian19",
  --"caged-arthurian20",
  --"caged-arthurian21",
  --"caged-arthurian22",
  --"caged-arthurian23",
  --"caged-arthurian24",
  --"arthurian-egg1",
  --"arthurian-egg2",
  --"arthurian-egg3",
  --"arthurian-egg4",
  --"arthurian-egg5",
  --"arthurian-egg6",
  --"arthurian-egg7",
  --"arthurian-egg8",
  --"arthurian-egg9",
  --"arthurian-egg10",
  --"full render arthurians",
  --"arthurians to Bonemeal",
  --"Extract arthurian Meat",
  --"Extract arthurian brains",
  --"Extract arthurian skin",
  --"Extract arthurian bones",
  --"Extract arthurian guts",
  --"Extract arthurian blood",
  --"Extract arthurian lard",
  --"Extract brains from Improved arthurians",
  --"Extract bones from Improved arthurians",
  --"Extract bonemeal from Improved arthurians",
  --"Extract guts from Improved arthurians",
  --"Extract blood from Improved arthurians",
  --"Extract skin from Improved arthurians",
  --"Extract fat from Improved arthurians",
  --"Extract meat from Improved arthurians",
  --"caged-auog1",
  --"caged-auog2",
  --"caged-auog3",
  --"caged-auog4",
  --"caged-auog5",
  --"caged-auog6",
  --"caged-auog7",
  --"caged-auog8",
  --"caged-auog9",
  --"caged-auog10",
  --"caged-auog11",
  --"caged-auog12",
  --"caged-auog13",
  --"caged-auog14",
  --"caged-auog15",
  --"caged-auog16",
  --"caged-auog17",
  --"caged-auog18",
  --"caged-auog19",
  --"caged-auog20",
  --"caged-auog21",
  --"caged-auog22",
  --"caged-auog23",
  --"caged-auog24",
  --"auog-cub1",
  --"auog-cub2",
  --"auog-cub3",
  --"auog-cub4",
  --"auog-cub5",
  --"auog-cub6",
  --"auog-cub7",
  --"auog-cub8",
  --"auog-cub9",
  --"auog-cub10",
  --"auog-cub11",
  --"auog-cub12",
  --"auog-cub13",
  --"auog-cub14",
  --"full render auogs",
  --"auogs to Bonemeal",
  --"Extract auog Meat",
  --"Extract auog brains",
  --"Extract auog skin",
  --"Extract auog bones",
  --"Extract auog guts",
  --"Extract auog blood",
  --"Extract auog lard",
  --"Extract brains from Improved auogs",
  --"Extract bones from Improved auogs",
  --"Extract bonemeal from Improved auogs",
  --"Extract meat from Improved auogs",
  --"Extract guts from Improved auogs",
  --"Extract blood from Improved auogs",
  --"Extract skin from Improved auogs",
  --"Extract fat from Improved auogs",
  --"caged-dingrits1",
  --"caged-dingrits2",
  --"caged-dingrits3",
  --"caged-dingrits4",
  --"caged-dingrits5",
  --"caged-dingrits6",
  --"caged-dingrits7",
  --"caged-dingrits8",
  --"caged-dingrits9",
  --"caged-dingrits10",
  --"caged-dingrits11",
  --"caged-dingrits12",
  --"caged-dingrits13",
  --"caged-dingrits14",
  --"caged-dingrits15",
  --"caged-dingrits16",
  --"caged-dingrits17",
  --"caged-dingrits18",
  --"caged-dingrits19",
  --"caged-dingrits20",
  --"dingrits-cub1",
  --"dingrits-cub2",
  --"dingrits-cub3",
  --"dingrits-cub4",
  --"dingrits-cub5",
  --"dingrits-cub6",
  --"dingrits-cub7",
  --"dingrits-cub8",
  --"dingrits-cub9",
  --"dingrits-cub10",
  --"dingrits-cub11",
  --"dingrits-cub12",
  --"dingrits-cub13",
  --"dingrits-cub14",
  --"full render dingrits",
  --"Extract dingrits Meat",
  --"Extract dingrits brains",
  --"Extract dingrits bones",
  --"Extract dingrits guts",
  --"Extract dingrits blood",
  --"Extract dingrits Pelt",
  --"Extract dingrits Spikes",
  --"Extract brains from Improved dingrits",
  --"Extract bones from Improved dingrits",
  --"Extract guts from Improved dingrits",
  --"Extract blood from Improved dingrits",
  --"Extract meat from Improved dingrits",
  --"caged-kmauts1",
  --"caged-kmauts2",
  --"caged-kmauts3",
  --"caged-kmauts4",
  --"caged-kmauts5",
  --"caged-kmauts6",
  --"caged-kmauts7",
  --"caged-kmauts8",
  --"caged-kmauts9",
  --"caged-kmauts10",
  --"caged-kmauts11",
  --"caged-kmauts12",
  --"caged-kmauts13",
  --"caged-kmauts14",
  --"caged-kmauts15",
  --"caged-kmauts16",
  --"caged-kmauts17",
  --"kmauts-cub1",
  --"kmauts-cub2",
  --"kmauts-cub3",
  --"kmauts-cub4",
  --"kmauts-cub5",
  --"kmauts-cub6",
  --"kmauts-cub7",
  --"kmauts-cub8",
  --"full render kmauts",
  --"Extract kmauts Meat",
  --"Extract kmauts brains",
  --"Extract kmauts tendons",
  --"Extract kmauts tendons-1",
  --"Extract kmauts guts",
  --"Extract kmauts blood",
  --"Extract kmauts lard",
  --"Extract brains from Improved kmauts",
  --"Extract guts from Improved kmauts",
  --"Extract blood from Improved kmauts",
  --"Extract meat from Improved kmauts",
  --"Extract fat from Improved kmauts",
  --"dhilmos1",
  --"dhilmos2",
  --"dhilmos3",
  --"dhilmos4",
  --"dhilmos5",
  --"dhilmos6",
  --"dhilmos7",
  --"dhilmos8",
  --"dhilmos9",
  --"dhilmos10",
  --"dhilmos11",
  --"dhilmos12",
  --"dhilmos13",
  --"dhilmos14",
  --"dhilmos15",
  --"dhilmos16",
  --"dhilmos17",
  --"dhilmos18",
  --"dhilmos-egg1",
  --"dhilmos-egg2",
  --"dhilmos-egg3",
  --"dhilmos-egg4",
  --"dhilmos-egg5",
  --"dhilmos-egg6",
  --"dhilmos-egg7",
  --"dhilmos-egg8",
  --"dhilmos-egg9",
  --"dhilmos-egg10",
  --"full render dhilmoss",
  --"Extract dhilmos Meat",
  --"Extract dhilmos guts",
  --"Extract dhilmos blood",
  --"Extract dhilmos lard",
  --"Extract dhilmos chitin",
  --"Extract meat from Improved dhilmoss",
  --"Extract guts from Improved dhilmoss",
  --"Extract blood from Improved dhilmoss",
  --"Extract fat from Improved dhilmoss",
  --"caged-scrondrix1",
  --"caged-scrondrix2",
  --"caged-scrondrix3",
  --"caged-scrondrix4",
  --"caged-scrondrix5",
  --"caged-scrondrix6",
  --"caged-scrondrix7",
  --"caged-scrondrix8",
  --"caged-scrondrix9",
  --"caged-scrondrix10",
  --"caged-scrondrix11",
  --"caged-scrondrix12",
  --"caged-scrondrix13",
  --"caged-scrondrix14",
  --"caged-scrondrix15",
  --"caged-scrondrix16",
  --"caged-scrondrix17",
  --"caged-scrondrix18",
  --"caged-scrondrix19",
  --"caged-scrondrix20",
  --"caged-scrondrix21",
  --"caged-scrondrix22",
  --"scrondrix-cub1",
  --"scrondrix-cub2",
  --"scrondrix-cub3",
  --"scrondrix-cub4",
  --"scrondrix-cub5",
  --"scrondrix-cub6",
  --"scrondrix-cub7",
  --"scrondrix-cub8",
  --"scrondrix-cub9",
  --"scrondrix-cub10",
  --"full render scrondrixs",
  --"Extract scrondrix Meat",
  --"Extract scrondrix brains",
  --"Extract scrondrix Pineal Gland",
  --"Extract scrondrix Pineal Gland-1",
  --"Extract scrondrix skin",
  --"Extract scrondrix bones",
  --"Extract scrondrix guts",
  --"Extract scrondrix blood",
  --"Extract scrondrix lard",
  --"Extract brains from Improved scrondrixs",
  --"Extract bones from Improved scrondrixs",
  --"Extract guts from Improved scrondrixs",
  --"Extract blood from Improved scrondrixs",
  --"Extract skin from Improved scrondrixs",
  --"Extract fat from Improved scrondrixs",
  --"Extract meat from Improved scrondrixs",
  --"caged-phadai1",
  --"caged-phadai2",
  --"caged-phadai3",
  --"caged-phadai4",
  --"caged-phadai5",
  --"caged-phadai6",
  --"caged-phadai7",
  --"caged-phadai8",
  --"caged-phadai9",
  --"caged-phadai10",
  --"caged-phadai11",
  --"caged-phadai12",
  --"caged-phadai13",
  --"caged-phadai14",
  --"caged-phadai15",
  --"caged-phadai16",
  --"caged-phadai17",
  --"caged-phadai18",
  --"caged-phadai19",
  --"caged-phadai20",
  --"caged-phadai21",
  --"caged-phadai22",
  --"caged-phadai23",
  --"caged-phadai24",
  --"phadai-pup1",
  --"phadai-pup2",
  --"phadai-pup3",
  --"phadai-pup4",
  --"phadai-pup5",
  --"phadai-pup6",
  --"phadai-pup7",
  --"phadai-pup8",
  --"phadai-pup9",
  --"phadai-pup10",
  --"phadai-pup11",
  --"phadai-pup12",
  --"phadai-pup13",
  --"phadai-pup14",
  --"full render phadais",
  --"Extract phadai Meat",
  --"Extract phadai brains",
  --"Extract phadai bones",
  --"Extract phadai guts",
  --"Extract phadai blood",
  --"Extract phadai Fat",
  --"Extract phadai Carapace",
  --"Extract phadai Skin",
  --"Extract brains from Improved phadais",
  --"Extract bones from Improved phadais",
  --"Extract guts from Improved phadais",
  --"Extract blood from Improved phadais",
  --"Extract meat from Improved phadais",
  --"Extract skin from Improved phadais",
  --"Extract fat from Improved phadais",
  --"auog-manure-1",
  --"auog-manure-2",
  --"auog-manure-3",
  --"auog-manure-4",
  --"auog-manure-5",
  --"auog-manure-6",
  --"auog-manure-7",
  --"auog-manure-1a",
  --"auog-manure-2a",
  --"auog-manure-3a",
  --"auog-manure-4a",
  --"auog-manure-5a",
  --"auog-manure-6a",
  --"auog-manure-7a",
  --"auog-manure-1b",
  --"auog-manure-2b",
  --"auog-manure-3b",
  --"auog-manure-4b",
  --"auog-manure-5b",
  --"auog-manure-6b",
  --"auog-manure-7b",
  --"manure-1",
  --"manure-2",
  --"manure-3",
  --"manure-4",
  --"manure-5",
  --"manure-6",
  --"manure-7",
  --"manure-1a",
  --"manure-2a",
  --"manure-3a",
  --"manure-4a",
  --"manure-5a",
  --"manure-6a",
  --"manure-7a",
  --"manure-1b",
  --"manure-2b",
  --"manure-3b",
  --"manure-4b",
  --"manure-5b",
  --"manure-6b",
  --"manure-7b",
  --"muk-manure-1",
  --"muk-manure-2",
  --"muk-manure-3",
  --"muk-manure-4",
  --"muk-manure-5",
  --"muk-manure-6",
  --"muk-manure-7",
  --"muk-manure-1a",
  --"muk-manure-2a",
  --"muk-manure-3a",
  --"muk-manure-4a",
  --"muk-manure-5a",
  --"muk-manure-6a",
  --"muk-manure-7a",
  --"muk-manure-1b",
  --"muk-manure-2b",
  --"muk-manure-3b",
  --"muk-manure-4b",
  --"muk-manure-5b",
  --"muk-manure-6b",
  --"muk-manure-7b",
  --"scrondrix-manure-1",
  --"scrondrix-manure-2",
  --"scrondrix-manure-3",
  --"scrondrix-manure-4",
  --"scrondrix-manure-5",
  --"scrondrix-manure-6",
  --"scrondrix-manure-1a",
  --"scrondrix-manure-2a",
  --"scrondrix-manure-3a",
  --"scrondrix-manure-4a",
  --"scrondrix-manure-5a",
  --"scrondrix-manure-6a",
  --"scrondrix-manure-1b",
  --"scrondrix-manure-2b",
  --"scrondrix-manure-3b",
  --"scrondrix-manure-4b",
  --"scrondrix-manure-5b",
  --"scrondrix-manure-6b",
  --"dingrits",
  "dingrits-codex",
  "earth-wolf-sample",
  "dingrits-food-01",
  "dingrits-food-02",
  --"dingrits-mature-01",
  --"dingrits-mature-02",
  --"caged-dingrits",
  --"uncaged-dingrits",
  --"charged-dingrit",
  --"dingrits-mk02",
  --"dingrits-mk03",
  --"dingrits-mk04",
  --"kmauts",
  "kmauts-codex",
  --"kmauts-mature-01",
  --"kmauts-mature-02",
  --"caged-kmauts",
  --"uncaged-kmauts",
  --"kmauts-mk02",
  --"kmauts-mk03",
  --"kmauts-mk04",
  --"vonix",
  "vonix-codex",
  --"vonix-grow-01",
  --"vonix-mature-01",
  --"vonix-mature-02",
  --"vonix-mk02",
  --"vonix-mk03",
  --"vonix-mk04",
  "grod-sample",
  "grod-codex",
  "earth-jute-sample",
  --"grod-seeds",
  --"replicator-grod",
  --"grod-mk02",
  --"grod-mk03",
  --"grod-mk04",
  --"phagnot",
  "phagnot-codex",
  "earth-giraffe-sample",
  "phagnot-food-01",
  "phagnot-food-02",
  --"phagnot-mature-01",
  --"phagnot-mature-02",
  --"caged-phagnot",
  --"uncaged-phagnot",
  --"phagnot-mk02",
  --"phagnot-mk03",
  --"phagnot-mk04",
  --"phag-manure-1",
  --"phag-manure-2",
  --"phag-manure-3",
  --"phag-manure-4",
  --"phag-manure-5",
  --"phag-manure-6",
  --"phag-manure-7",
  --"phag-manure-1a",
  --"phag-manure-2a",
  --"phag-manure-3a",
  --"phag-manure-4a",
  --"phag-manure-5a",
  --"phag-manure-6a",
  --"phag-manure-7a",
  --"phag-manure-1b",
  --"phag-manure-2b",
  --"phag-manure-3b",
  --"phag-manure-4b",
  --"phag-manure-5b",
  --"phag-manure-6b",
  --"phag-manure-7b",
  "bhoddos-sample",
  "bhoddos-codex",
  --"bhoddos-spore",
  --"bhoddos-mk02",
  --"bhoddos-mk03",
  --"bhoddos-mk04",
  --"xeno",
  "xeno-codex",
  "arqad-codex",
  --"xeno-mature-01",
  --"xeno-mature-02",
  --"caged-xeno",
  --"uncaged-xeno",
  --"xeno-mk02",
  --"xeno-mk03",
  --"xeno-mk04",
  "cridren-sample",
  "cridren-codex",
  "earth-venus-fly-sample",
  --"cridren-seeds",
  --"zipir1",
  "zipir-codex",
  "earth-crustacean-sample",
  "zipir-food-01",
  "zipir-food-02",
  --"zipir-grow-01",
  --"zipir-mature-01",
  --"zipir-mature-02",
  --"zipir-mk02",
  --"zipir-mk03",
  --"zipir-mk04",
  --"trits",
  "trits-codex",
  --"trits-mature-01",
  --"trits-mature-02",
  --"trits-mk02",
  --"trits-mk03",
  --"trits-mk04",
  --"xyhiphoe",
  "xyhiphoe-codex",
  --"xyhiphoe-mature-01",
  --"xyhiphoe-mature-02",
  --"xyhiphoe-mk02",
  --"xyhiphoe-mk03",
  --"xyhiphoe-mk04",
  --"auog-recharge",
  --"auog-recharge-2",
  --"auog-mk02-recharge",
  --"auog-mk02-recharge-2",
  --"auog-mk03-recharge",
  --"auog-mk03-recharge-2",
  --"auog-mk04-recharge",
  --"auog-mk04-recharge-2",
  --"dingrit-recharge",
  --"dingrit-recharge-2",
  --"dingrit-mk02-recharge",
  --"dingrit-mk02-recharge-2",
  --"dingrit-mk03-recharge",
  --"dingrit-mk03-recharge-2",
  --"dingrit-mk04-recharge",
  --"dingrit-mk04-recharge-2",
  --"logistic-science-01",
  --"chemical-science-01",
  --"production-science-01",
  --"utility-science-01",
  --"phag-carapace-1",
  --"phag-carapace-2",
  --"phag-carapace-3",
  --"phag-carapace-4",
  --"phag-carapace-5",
  --"phag-carapace-6",
  --"phag-carapace-7",
  --"ralesia-super-1",
  --"ralesia-super-2",
  --"ralesia-super-3",
  --"ralesia-super-4",
  --"ralesia-super-5",
  --"ralesia-super-6",
  --"ralesia-super-7",
  --"ralesia-super-10",
  --"rennea-super-1",
  --"rennea-super-2",
  --"rennea-super-3",
  --"rennea-super-4",
  --"rennea-super-5",
  --"rennea-super-6",
  --"rennea-super-7",
  --"rennea-super-10",
  --"tuuphra-super-1",
  --"tuuphra-super-2",
  --"tuuphra-super-3",
  --"tuuphra-super-4",
  --"tuuphra-super-5",
  --"tuuphra-super-6",
  --"tuuphra-super-7",
  --"tuuphra-super-10",
  --"grod-super-1",
  --"grod-super-2",
  --"grod-super-3",
  --"grod-super-4",
  --"grod-super-5",
  --"grod-super-6",
  --"grod-super-7",
  --"grod-super-8",
  --"grod-super-10",
  --"yotoi-super-1",
  --"yotoi-super-2",
  --"yotoi-super-3",
  --"yotoi-super-4",
  --"yotoi-super-5",
  --"yotoi-super-6",
  --"yotoi-super-7",
  --"yotoi-super-8",
  --"yotoi-super-10",
  --"yotoi-fruit-super-3",
  --"yotoi-fruit-super-4",
  --"yotoi-fruit-super-5",
  --"yotoi-fruit-super-6",
  --"yotoi-fruit-super-7",
  --"yotoi-fruit-super-8",
  --"yotoi-fruit-super-10",
  --"bioreserve-super-1",
  --"bioreserve-super-2",
  --"bioreserve-super-3",
  --"bioreserve-super-4",
  --"bioreserve-super-5",
  --"bioreserve-super-6",
  --"bioreserve-super-7",
  --"zipir-a1",
  --"zipir-a2",
  --"zipir-a3",
  --"zipir-a4",
  --"zipir-a5",
  --"zipir-a6",
  --"zipir-a7",
  --"zipir-a8",
  --"zipir-a9",
  --"zipir-a10",
  --"zipir-a11",
  --"zipir-a12",
  --"zipir-a13",
  --"zipir-a14",
  --"zipir-a15",
  --"zipir-a16",
  --"zipir-a17",
  --"zipir-a18",
  --"zipir-a19",
  --"zipir-a20",
  --"zipir-a21",
  --"zipir-egg1",
  --"zipir-egg2",
  --"zipir-egg3",
  --"zipir-egg4",
  --"zipir-egg5",
  --"zipir-egg6",
  --"zipir-egg7",
  --"zipir-egg8",
  --"zipir-egg9",
  --"zipir-egg10",
  --"full render zipir",
  --"Extract zipir Meat",
  --"Extract zipir brain",
  --"Extract zipir skin",
  --"Extract zipir guts",
  --"Extract zipir blood",
  --"Extract zipir lard",
  --"Extract brains from Improved Zipir",
  --"Extract guts from Improved Zipir",
  --"Extract Arthropod blood from Improved Zipir",
  --"Extract skin from Improved Zipir",
  --"Extract fat from Improved Zipir",
  --"Extract meat from Improved Zipir",
  --"xyhiphoe1",
  --"xyhiphoe2",
  --"xyhiphoe3",
  --"xyhiphoe4",
  --"xyhiphoe5",
  --"xyhiphoe6",
  --"xyhiphoe7",
  --"xyhiphoe8",
  --"xyhiphoe9",
  --"xyhiphoe10",
  --"xyhiphoe11",
  --"xyhiphoe12",
  --"xyhiphoe13",
  --"xyhiphoe14",
  --"xyhiphoe15",
  --"xyhiphoe16",
  --"xyhiphoe17",
  --"xyhiphoe18",
  --"xyhiphoe-cub1",
  --"xyhiphoe-cub2",
  --"xyhiphoe-cub3",
  --"xyhiphoe-cub4",
  --"xyhiphoe-cub5",
  --"xyhiphoe-cub6",
  --"xyhiphoe-cub7",
  --"xyhiphoe-cub8",
  --"xyhiphoe-cub9",
  --"xyhiphoe-cub10",
  --"xyhiphoe-cub11",
  --"xyhiphoe-cub12",
  --"xyhiphoe-cub13",
  --"xyhiphoe-cub14",
  --"full render xyhiphoe",
  --"Extract xyhiphoe Meat",
  --"Extract xyhiphoe shell",
  --"Extract xyhiphoe guts",
  --"Extract xyhiphoe blood",
  --"Extract meat from Improved xyhiphoe",
  --"Extract guts from Improved xyhiphoe",
  --"Extract blood from Improved xyhiphoe",
  --"Extract shell from Improved xyhiphoe",
  --"trits1",
  --"trits2",
  --"trits3",
  --"trits4",
  --"trits5",
  --"trits6",
  --"trits7",
  --"trits8",
  --"trits9",
  --"trits10",
  --"trits11",
  --"trits12",
  --"trits13",
  --"trits14",
  --"trits15",
  --"trits16",
  --"trits17",
  --"trits18",
  --"trits19",
  --"trits20",
  --"trits21",
  --"trits22",
  --"trits23",
  --"trits24",
  --"trits-cub1",
  --"trits-cub2",
  --"trits-cub3",
  --"trits-cub4",
  --"trits-cub5",
  --"trits-cub6",
  --"trits-cub7",
  --"trits-cub8",
  --"trits-cub9",
  --"trits-cub10",
  --"trits-cub11",
  --"trits-cub12",
  --"trits-cub13",
  --"trits-cub14",
  --"full render Trits",
  --"Extract Trits Meat",
  --"Extract Trits brains",
  --"Extract Trits skin",
  --"Extract Trits bones",
  --"Extract Trits guts",
  --"Extract Trits blood",
  --"Extract Trits lard",
  --"Extract brains from Improved Trits",
  --"Extract bones from Improved Trits",
  --"Extract meat from Improved Trits",
  --"Extract guts from Improved Trits",
  --"Extract blood from Improved Trits",
  --"Extract skin from Improved Trits",
  --"Extract fat from Improved Trits",
  --"caged-xeno1",
  --"caged-xeno2",
  --"caged-xeno3",
  --"caged-xeno4",
  --"caged-xeno5",
  --"caged-xeno6",
  --"caged-xeno7",
  --"caged-xeno8",
  --"caged-xeno9",
  --"caged-xeno10",
  --"caged-xeno11",
  --"caged-xeno12",
  --"caged-xeno13",
  --"caged-xeno14",
  --"caged-xeno15",
  --"caged-xeno16",
  --"caged-xeno17",
  --"caged-xeno18",
  --"caged-xeno19",
  --"caged-xeno20",
  --"xeno-egg1",
  --"xeno-egg2",
  --"xeno-egg3",
  --"xeno-egg4",
  --"xeno-egg5",
  --"xeno-egg6",
  --"xeno-egg7",
  --"xeno-egg8",
  --"xeno-egg9",
  --"xeno-egg10",
  --"full render Xenos",
  --"Extract Xeno Meat",
  --"Extract Xeno brains",
  --"Extract xeno chitin",
  --"Extract Xeno bones",
  --"Extract Xeno blood",
  --"Extract brains from Improved Xenos",
  --"Extract bones from Improved xenos",
  --"Extract bonemeal from Improved Xenos",
  --"Extract blood from Improved Xenos",
  --"Extract Chitin from Improved xenos",
  --"Extract meat from Improved Xenos",
  --"vrauks1",
  --"vrauks2",
  --"vrauks3",
  --"vrauks4",
  --"vrauks5",
  --"vrauks6",
  --"vrauks7",
  --"vrauks8",
  --"vrauks9",
  --"vrauks10",
  --"vrauks11",
  --"vrauks12",
  --"vrauks13",
  --"vrauks14",
  --"vrauks15",
  --"vrauks16",
  --"vrauks17",
  --"vrauks18",
  --"vrauks19",
  --"vrauks20",
  --"vrauks-coccon1",
  --"vrauks-coccon2",
  --"vrauks-coccon3",
  --"vrauks-coccon4",
  --"vrauks-coccon5",
  --"vrauks-coccon6",
  --"vrauks-coccon7",
  --"vrauks-coccon8",
  --"vrauks-coccon9",
  --"vrauks-coccon10",
  --"vrauks-coccon11",
  --"vrauks-coccon12",
  --"vrauks-coccon13",
  --"vrauks-coccon14",
  --"full render Vrauks",
  --"Extract Vrauks Meat",
  --"Extract Vrauks brains",
  --"Extract Vrauks chithin",
  --"Extract Vrauks guts",
  --"Extract Vrauks blood",
  --"Extract brains from Improved Vrauks",
  --"Extract meat from Improved Vrauks",
  --"Extract guts from Improved Vrauks",
  --"Extract blood from Improved Vrauks",
  --"Extract skin from Improved Vrauks",
  --"full render arthuriansb",
  --"Extract arthurian brainsb",
  --"full render auogsb",
  --"Extract auog brainsb",
  --"full render dingritsb",
  --"Extract dingrits brainsb",
  --"full render kmautsb",
  --"Extract kmauts brainsb",
  --"full render Mukmouxsb",
  --"Extract Mukmoux brainsb",
  --"full render phadaisb",
  --"Extract phadai brainsb",
  --"full render phagnotsb",
  --"Extract phagnot brainsb",
  --"full render scrondrixsb",
  --"Extract scrondrix brainsb",
  --"full render Tritsb",
  --"Extract Trits brainsb",
  --"full render Ulricsb",
  --"Extract Ulric brainsb",
  --"full render Vonixb",
  --"Extract Vonix brainb",
  --"full render Vrauksb",
  --"Extract Vrauks brainsb",
  --"full render Xenosb",
  --"Extract Xeno brainsb",
  --"full render zipirb",
  --"Extract zipir brainb",
  --"Extract arthurian brains-2",
  --"Extract brains from Improved arthurians-2",
  --"Extract auog brains-2",
  --"Extract brains from Improved auogs-2",
  --"Extract dingrits brains-2",
  --"Extract brains from Improved dingrits-2",
  --"Extract kmauts brains-2",
  --"Extract brains from Improved kmauts-2",
  --"Extract Mukmoux brains-2",
  --"Extract brains from Improved Mukmouxs-2",
  --"Extract phadai brains-2",
  --"Extract brains from Improved phadais-2",
  --"Extract phagnot brains-2",
  --"Extract brains from Improved phagnots-2",
  --"Extract scrondrix brains-2",
  --"Extract brains from Improved scrondrixs-2",
  --"Extract Trits brains-2",
  --"Extract brains from Improved Trits-2",
  --"Extract Ulric brains-2",
  --"Extract brains from Improved Ulrics-2",
  --"Extract Vonix brain-2",
  --"Extract brains from Improved Vonixes-2",
  --"Extract Vrauks brains-2",
  --"Extract brains from Improved Vrauks-2",
  --"Extract Xeno brains-2",
  --"Extract brains from Improved Xenos-2",
  --"Extract zipir brain-2",
  --"Extract brains from Improved Zipir-2",
  --"Extract arthurian Meat-1",
  --"Extract auog Meat-1",
  --"Extract dhilmos Meat-1",
  --"Extract dingrits Meat-1",
  --"Extract kmauts Meat-1",
  --"Extract Mukmoux Meat-1",
  --"Extract phadai Meat-1",
  --"Extract phagnot Meat-1",
  --"Extract scrondrix Meat-1",
  --"Extract Trits Meat-1",
  --"Extract Ulric Meat-1",
  --"Extract Vonix Meat-1",
  --"Extract Vrauks Meat-1",
  --"Extract Xeno Meat-1",
  --"Extract xyhiphoe Meat-1",
  --"Extract zipir Meat-1",
  --"Extract arthurian Meat-2",
  --"Extract meat from Improved arthurians-2",
  --"Extract auog Meat-2",
  --"Extract meat from Improved auogs-2",
  --"Extract dhilmos Meat-2",
  --"Extract meat from Improved dhilmoss-2",
  --"Extract dingrits Meat-2",
  --"Extract meat from Improved dingrits-2",
  --"Extract kmauts Meat-2",
  --"Extract meat from Improved kmauts-2",
  --"Extract Mukmoux Meat-2",
  --"Extract meat from Improved Mukmouxs-2",
  --"Extract phadai Meat-2",
  --"Extract meat from Improved phadais-2",
  --"Extract phagnot Meat-2",
  --"Extract meat from Improved phagnots-2",
  --"Extract scrondrix Meat-2",
  --"Extract meat from Improved scrondrixs-2",
  --"Extract Trits Meat-2",
  --"Extract meat from Improved Trits-2",
  --"Extract Ulric Meat-2",
  --"Extract meat from Improved Ulrics-2",
  --"Extract Vonix Meat-2",
  --"Extract meat from Improved Vonixes-2",
  --"Extract Vrauks Meat-2",
  --"Extract meat from Improved Vrauks-2",
  --"Extract Xeno Meat-2",
  --"Extract meat from Improved Xenos-2",
  --"Extract xyhiphoe Meat-2",
  --"Extract meat from Improved xyhiphoe-2",
  --"Extract zipir Meat-2",
  --"Extract meat from Improved Zipir-2",
  --"Extract arthurian bones-1",
  --"Extract auog bones-1",
  --"Extract dingrits bones-1",
  --"Extract Mukmoux bones-1",
  --"Extract phadai bones-1",
  --"Extract phagnot bones-1",
  --"Extract scrondrix bones-1",
  --"Extract Trits bones-1",
  --"Extract Ulric bones-1",
  --"Extract Xeno bones-1",
  --"Extract arthurian bones-2",
  --"Extract bones from Improved arthurians-2",
  --"Extract auog bones-2",
  --"Extract bones from Improved auogs-2",
  --"Extract dingrits bones-2",
  --"Extract bones from Improved dingrits-2",
  --"Extract Mukmoux bones-2",
  --"Extract bones from Improved Mukmouxs-2",
  --"Extract phadai bones-2",
  --"Extract bones from Improved phadais-2",
  --"Extract phagnot bones-2",
  --"Extract bones from Improved phagnots-2",
  --"Extract scrondrix bones-2",
  --"Extract bones from Improved scrondrixs-2",
  --"Extract Trits bones-2",
  --"Extract bones from Improved Trits-2",
  --"Extract Ulric bones-2",
  --"Extract bones from Improved Ulrics-2",
  --"Extract Xeno bones-2",
  --"Extract bones from Improved xenos-2",
  --"Extract arthurian guts-1",
  --"Extract auog guts-1",
  --"Extract dhilmos guts-1",
  --"Extract dingrits guts-1",
  --"Extract kmauts guts-1",
  --"Extract Mukmoux guts-1",
  --"Extract phadai guts-1",
  --"Extract phagnot guts-1",
  --"Extract scrondrix guts-1",
  --"Extract Trits guts-1",
  --"Extract Ulric guts-1",
  --"Extract Vonix guts-1",
  --"Extract Vrauks guts-1",
  --"Extract xyhiphoe guts-1",
  --"Extract zipir guts-1",
  --"Extract arthurian guts-2",
  --"Extract guts from Improved arthurians-2",
  --"Extract auog guts-5",
  --"Extract guts from Improved auogs-2",
  --"Extract dhilmos guts-2",
  --"Extract guts from Improved dhilmoss-2",
  --"Extract dingrits guts-2",
  --"Extract guts from Improved dingrits-2",
  --"Extract kmauts guts-2",
  --"Extract guts from Improved kmauts-2",
  --"Extract Mukmoux guts-2",
  --"Extract guts from Improved Mukmouxs-2",
  --"Extract phadai guts-2",
  --"Extract guts from Improved phadais-2",
  --"Extract phagnot guts-2",
  --"Extract guts from Improved phagnots-2",
  --"Extract scrondrix guts-2",
  --"Extract guts from Improved scrondrixs-2",
  --"Extract Trits guts-2",
  --"Extract guts from Improved Trits-2",
  --"Extract Ulric guts-2",
  --"Extract guts from Improved Ulrics-2",
  --"Extract Vonix guts-2",
  --"Extract guts from Improved Vonixes-2",
  --"Extract Vrauks guts-2",
  --"Extract guts from Improved Vrauks-2",
  --"Extract xyhiphoe guts-2",
  --"Extract guts from Improved xyhiphoe-2",
  --"Extract zipir guts-2",
  --"Extract guts from Improved Zipir-2",
  --"Extract arthurian blood-1",
  --"Extract auog blood-1",
  --"Extract dhilmos blood-1",
  --"Extract dingrits blood-1",
  --"Extract kmauts blood-1",
  --"Extract Mukmoux blood-1",
  --"Extract phadai blood-1",
  --"Extract phagnot blood-1",
  --"Extract scrondrix blood-1",
  --"Extract Trits blood-1",
  --"Extract Ulric blood-1",
  --"Extract Vonix blood-1",
  --"Extract Vrauks blood-1",
  --"Extract Xeno blood-1",
  --"Extract xyhiphoe blood-1",
  --"Extract zipir blood-1",
  --"Extract arthurian blood-2",
  --"Extract blood from Improved arthurians-2",
  --"Extract auog blood-2",
  --"Extract blood from Improved auogs-2",
  --"Extract dhilmos blood-2",
  --"Extract blood from Improved dhilmoss-2",
  --"Extract dingrits blood-2",
  --"Extract blood from Improved dingrits-2",
  --"Extract kmauts blood-2",
  --"Extract blood from Improved kmauts-2",
  --"Extract Mukmoux blood-2",
  --"Extract blood from Improved Mukmouxs-2",
  --"Extract phadai blood-2",
  --"Extract blood from Improved phadais-2",
  --"Extract phagnot blood-2",
  --"Extract blood from Improved phagnots-2",
  --"Extract scrondrix blood-2",
  --"Extract blood from Improved scrondrixs-2",
  --"Extract Trits blood-2",
  --"Extract blood from Improved Trits-1",
  --"Extract Ulric blood-2",
  --"Extract blood from Improved Ulrics-2",
  --"Extract Vonix blood-2",
  --"Extract Arthropod blood from Improved Vonixes-2",
  --"Extract Vrauks blood-2",
  --"Extract blood from Improved Vrauks-2",
  --"Extract Xeno blood-2",
  --"Extract blood from Improved Xenos-2",
  --"Extract xyhiphoe blood-2",
  --"Extract blood from Improved xyhiphoe-2",
  --"Extract zipir blood-2",
  --"Extract Arthropod blood from Improved Zipir-2",
  --"Extract arthurian skin-1",
  --"Extract auog skin-1",
  --"Extract dhilmos chitin-1",
  --"Extract Mukmoux skin-1",
  --"Extract phadai Skin-1",
  --"Extract phagnot skin-1",
  --"Extract scrondrix skin-1",
  --"Extract Trits skin-1",
  --"Extract Ulric skin-1",
  --"Extract Vonix skin-1",
  --"Extract Vrauks chithin-1",
  --"Extract xeno chitin-1",
  --"Extract zipir skin-1",
  --"Extract arthurian skin-2",
  --"Extract skin from Improved arthurians-2",
  --"Extract auog skin-2",
  --"Extract skin from Improved auogs-2",
  --"Extract dhilmos chitin-2",
  --"Extract Mukmoux skin-2",
  --"Extract skin from Improved Mukmouxs-2",
  --"Extract phadai Skin-2",
  --"Extract skin from Improved phadais-2",
  --"Extract phagnot skin-2",
  --"Extract skin from Improved phagnots-2",
  --"Extract scrondrix skin-2",
  --"Extract skin from Improved scrondrixs-2",
  --"Extract Trits skin-2",
  --"Extract skin from Improved Trits-2",
  --"Extract Ulric skin-2",
  --"Extract skin from Improved Ulrics-2",
  --"Extract Vonix skin-2",
  --"Extract skin from Improved Vonixes-2",
  --"Extract Vrauks chithin-2",
  --"Extract skin from Improved Vrauks-2",
  --"Extract xeno chitin-2",
  --"Extract Chitin from Improved xenos-2",
  --"Extract zipir skin-2",
  --"Extract skin from Improved Zipir-2",
  --"Extract arthurian lard-1",
  --"Extract auog lard-1",
  --"Extract dhilmos lard-1",
  --"Extract kmauts lard-1",
  --"Extract Mukmoux lard-1",
  --"Extract phadai Fat-1",
  --"Extract scrondrix lard-1",
  --"Extract Trits lard-1",
  --"Extract Ulric lard-1",
  --"Extract Vonix lard-1",
  --"Extract zipir lard-1",
  --"Extract arthurian lard-2",
  --"Extract fat from Improved arthurians-2",
  --"Extract auog lard-2",
  --"Extract fat from Improved auogs-2",
  --"Extract dhilmos lard-2",
  --"Extract fat from Improved dhilmoss-2",
  --"Extract kmauts lard-2",
  --"Extract fat from Improved kmauts-2",
  --"Extract Mukmoux lard-2",
  --"Extract fat from Improved Mukmouxs-2",
  --"Extract phadai Fat-2",
  --"Extract fat from Improved phadais-2",
  --"Extract scrondrix lard-2",
  --"Extract fat from Improved scrondrixs-2",
  --"Extract Trits lard-2",
  --"Extract fat from Improved Trits-2",
  --"Extract Ulric lard-2",
  --"Extract fat from Improved Ulrics-2",
  --"Extract Vonix lard-2",
  --"Extract fat from Improved Vonixes-2",
  --"Extract zipir lard-2",
  --"Extract fat from Improved Zipir-2",
  --"gas-bladder-to-acetylene",
  --"gas-bladder-to-rich-gas",
  --"gas-bladder-to-helium",
  --"gas-bladder-to-co2",
  --"gas-bladder-to-chlorine",
  --"gas-bladder-to-hydrogen",
  --"Extract phagnot Gas bladder-2",
  "starch-b",
  "starch-2-b",
  "fertilizer-3",
  "antelope-enclosure-mk01",
  --"kicalk-super-1",
  --"kicalk-super-2",
  --"kicalk-super-3",
  --"kicalk-super-4",
  --"kicalk-super-5",
  --"kicalk-super-6",
  --"kicalk-super-7",
  --"kicalk-super-8",
  --"kicalk-super-9",
  --"kicalk-super-10",
  "kicalk-sample",
  "kicalk-codex",
  "earth-palmtree-sample",
  --"kicalk-seeds",
  --"replicator-kicalk",
  --"kicalk-mk02",
  --"kicalk-mk03",
  --"kicalk-mk04",
  --"arum-super-1",
  --"arum-super-2",
  --"arum-super-3",
  --"arum-super-4",
  --"arum-super-5",
  --"arum-super-6",
  --"arum-super-7",
  --"arum-super-8",
  --"arum-super-9",
  --"arum-super-10",
  "cadaveric-arum-sample",
  "cadaveric-arum-codex",
  --"cadaveric-arum-seeds",
  --"cadaveric-processing-01",
  --"cadaveric-processing-02",
  --"cadaveric-processing-03",
  --"cadaveric-acidgas-01",
  --"replicator-cadaveric-arum",
  "cadavericarum-mk01",
  "cadavericarum-mk02",
  "cadavericarum-mk03",
  "cadavericarum-mk04",
  "kicalk-plantation-mk01",
  "kicalk-plantation-mk02",
  "kicalk-plantation-mk03",
  "kicalk-plantation-mk04",
  "antelope",
  "antelope-codex",
  "earth-antelope-sample",
  --"cage-antelope",
  --"caged-antelope1",
  --"caged-antelope2",
  --"caged-antelope3",
  --"caged-antelope4",
  --"caged-antelope5",
  --"caged-antelope6",
  --"caged-antelope7",
  --"caged-antelope8",
  --"full render Schrodinger antelopes",
  --"Extract antelope Meat",
  --"Extract antelope brains",
  --"Extract antelope skin",
  --"Extract antelope bones",
  --"Extract antelope guts",
  --"Extract antelope lard",
  --"Extract antelope strangelets",
  "fiber-b",
  "seaweed-8",
  "mukmoux-manure-03",
  "mukmoux-manure-03-food",
  "bones-to-phosphate",
  "carapace-to-re",
  "meat-to-cyanic",
  "kicalk-to-iron",
  "cadaveric-to-sulfur",
  "cadaveric-to-copper",
  "blood-to-urea",
  "ethylene-from-fruit",
  "fiber-01",
  "phenol-02",
  "filtration-media-4",
  "urea-from-liquid-manure",
  "yotoi-fiber",
  "kicalk-fiber",
  "cellulose-01",
  "methane-from-liquid-manure",
  --"ralesia-super-8",
  --"ralesia-super-9",
  --"rennea-super-8",
  --"rennea-super-9",
  --"tuuphra-super-8",
  --"tuuphra-super-9",
  --"grod-super-9",
  --"yotoi-super-9",
  --"yotoi-fruit-super-9",
  "chithin-to-phosphate",
  "meat-to-phosphate",
  "fish-to-phosphate",
  "wood-seeds-to-phosphate",
  "rennea-to-phosphate",
  --"gas-bladder-to-methane",
  --"gas-bladder-to-ammonia",
  --"gas-bladder-to-propene",
  --"gas-bladder-to-ethylene",
  "biopolymer-2",
  "phenol-3",
  "log-organics-2",
  "organics-from-wood-2",
  "soil-separation-2",
  "biomass-1-a",
  "dried-grods-02",
  "gas-bladder-to-natura-gas",
  "concrete-02"
	}

--adding to module limitation list
FUN.productivity(recipes_list)

--log(serpent.block(data.raw.recipe['korlex-milk-4b']))
--log(serpent.block(data.raw.recipe['korlex-milk-5b']))
--log(serpent.block(data.raw.recipe['korlex-milk-6b']))
--log(serpent.block(data.raw.recipe['korlex-milk-7b']))