require("__stdlib__/stdlib/data/data").Util.create_data_globals()

require("prototypes/item-groups")
require("prototypes/recipe-categories")

--(( Technology ))--
require("prototypes/technologies/xenobiology")
require("prototypes/technologies/mycology")
require("prototypes/technologies/microbiology")
require("prototypes/technologies/botany")
require("prototypes/technologies/biotech")
require("prototypes/technologies/genetics")
require("prototypes/technologies/zoology")
require("prototypes/technologies/land-animals")
require("prototypes/technologies/water-animals")
require("prototypes/technologies/water-invertebrates")
require("prototypes/technologies/water-gmo-animals")
require("prototypes/technologies/organic-breeding")
require("prototypes/technologies/molecular-decohesion")
require("prototypes/technologies/food")
require("prototypes/technologies/ulric")
require("prototypes/technologies/ralesia")
require("prototypes/technologies/mukmoux")
require("prototypes/technologies/tuuphra")
require("prototypes/technologies/arthurian")
require("prototypes/technologies/navens")
require("prototypes/technologies/yotoi")
require("prototypes/technologies/genetic-design")
require("prototypes/technologies/dhilmos")
require("prototypes/technologies/assisted-embryology")
require("prototypes/technologies/scrondrix")
require("prototypes/technologies/pharmagenomics")
require("prototypes/technologies/growth-hormone")
require("prototypes/technologies/rennea")
require("prototypes/technologies/phadai")
require("prototypes/technologies/auog")
require("prototypes/technologies/yaedols")

--(( BUILDINGS ))--
require("prototypes/buildings/moss-farm")
require("prototypes/buildings/seaweed-crop-mk01")
require("prototypes/buildings/moss-farm-mk02")
require("prototypes/buildings/spore-collector-mk01")
require("prototypes/buildings/fwf-mk01")
require("prototypes/buildings/micro-mine-mk01")
require("prototypes/buildings/biofactory-mk01")
require("prototypes/buildings/genlab-mk01")
require("prototypes/buildings/incubator-mk01")
require("prototypes/buildings/creature-chamber-mk01")
require("prototypes/buildings/vrauks-paddock-mk01")
require("prototypes/buildings/slaughterhouse-mk01")
require("prototypes/buildings/sponge-culture-mk01")
require("prototypes/buildings/ulric-corral-mk01")
require("prototypes/buildings/ralesia-plantation-mk01")
require("prototypes/buildings/tuuphra-plantation-mk01")
require("prototypes/buildings/mukmoux-pasture-mk01")
require("prototypes/buildings/arthurian-pen-mk01")
require("prototypes/buildings/data-array")
require("prototypes/buildings/navens-culture-mk01")
require("prototypes/buildings/yotoi-aloe-orchard-mk01")
require("prototypes/buildings/dhilmos-pool-mk01")
require("prototypes/buildings/scrondrix-pen-mk01")
require("prototypes/buildings/rennea-plantation-mk01")
require("prototypes/buildings/phadai-enclosure-mk01")
require("prototypes/buildings/auog-paddock-mk01")
require("prototypes/buildings/atomizer-mk01")
require("prototypes/buildings/fish-farm-mk01")
require("prototypes/buildings/yaedols-culture-mk01")

--test chest--
require("prototypes/buildings/test-filtered-chest-mk01")

--(( RECIPES ))--
require('prototypes/items/items')
require('prototypes/recipes/recipes')
require('prototypes/recipes/recipes-atomizer')
require('prototypes/recipes/recipes-mo')
require('prototypes/recipes/recipes-crops')
require('prototypes/recipes/recipes-seaweed')
require('prototypes/recipes/recipes-animals')
require('prototypes/recipes/recipes-ulric')
require('prototypes/recipes/recipes-sea-sponge')
--require('prototypes/recipes/recipes-ralesia')
require('prototypes/recipes/recipes-mukmoux')
require('prototypes/recipes/recipes-tuuphra')
require('prototypes/recipes/recipes-arthurian')
require('prototypes/recipes/recipes-navens')
require('prototypes/recipes/recipes-yotoi')
require('prototypes/recipes/recipes-dhilmos')
require('prototypes/recipes/recipes-scrondrix')
require('prototypes/recipes/recipes-rennea')
require('prototypes/recipes/recipes-phadai')
require('prototypes/recipes/recipes-auog')
require('prototypes/recipes/recipes-fish')
require('prototypes/recipes/recipes-yaedols')
require('prototypes/recipes/recipes-auto-ralesia')
require('prototypes/recipes/recipes-auto-fawogae')
require('prototypes/recipes/recipes-auto-ulric')
require('prototypes/recipes/recipes-ulric-products')


--(( FLUIDS ))--
require("prototypes/fluids/zogna-bacteria")
require("prototypes/fluids/blood")
require("prototypes/fluids/formamide")
require("prototypes/fluids/fetal-serum")
require("prototypes/fluids/artificial-blood")
require("prototypes/fluids/flutec-pp6")
require("prototypes/fluids/decalin")
require("prototypes/fluids/flavonoids")
require("prototypes/fluids/arthropod-blood")
require("prototypes/fluids/fish-oil")
