local turd_migrate = require "__pyalienlife__/scripts/turd/turd-migration"

turd_migrate("moondrop-upgrade", "cu")
turd_migrate("moondrop-upgrade", "moon")
turd_migrate("moondrop-upgrade", "carbon-capture")
turd_migrate("mukmoux-upgrade", "zero-cross")
turd_migrate("mukmoux-upgrade", "bip")
turd_migrate("mukmoux-upgrade", "think-collar")
turd_migrate("fawogae-upgrade", "n2-ferti")
turd_migrate("fawogae-upgrade", "acidosis")
turd_migrate("fawogae-upgrade", "dry")
turd_migrate("fast-wood-forestry-upgrade", "dry-storage")
turd_migrate("fast-wood-forestry-upgrade", "selective-heads")
turd_migrate("fast-wood-forestry-upgrade", "self-generation")
turd_migrate("atomizer-upgrade", "sc-core")
turd_migrate("atomizer-upgrade", "sub-atomic")
turd_migrate("atomizer-upgrade", "d-core")
turd_migrate("zungror-upgrade", "geooxidation")
turd_migrate("zungror-upgrade", "genooscillation")
turd_migrate("zungror-upgrade", "oviduct-bombardment")
