local turd_migrate = require '__pyalienlife__/scripts/turd/turd-migration'

turd_migrate('sap-upgrade', 'patch')
turd_migrate('bioprinting-upgrade', 'high-viability')
turd_migrate('bioprinting-upgrade', 'biomimetics')
turd_migrate('bioprinting-upgrade', 'covalent')
turd_migrate('rennea-upgrade', 'deadheading')
turd_migrate('rennea-upgrade', 'alltime')
turd_migrate('rennea-upgrade', 'aphid-cleaning')
turd_migrate('scrondrix-upgrade', 'boronb')
turd_migrate('scrondrix-upgrade', 'hspa')
turd_migrate('arthurian-upgrade', 'abacus')
turd_migrate('arthurian-upgrade', 'heated-stone')
turd_migrate('arthurian-upgrade', 'cannibalism')
turd_migrate('atomizer-upgrade', 'sub-atomic')
turd_migrate('kicalk-upgrade', 'wire-netting')
turd_migrate('moss-upgrade', 'spores')
turd_migrate('moss-upgrade', 'hd-moss')
turd_migrate('moss-upgrade', 'inbuilt-moss')
turd_migrate('moondrop-upgrade', 'cu')
turd_migrate('moondrop-upgrade', 'moon')
