local items = {}
items.inputs = {}
items.outputs = {}
--table.itemkey = {item, default item amount}

items.inputs.water = {'water', 100}
items.inputs.soil = {'soil', 10}
items.inputs.hydrogen = {'hydrogen', 10}
items.inputs.coarse = {'coarse', 10}
items.inputs.carbondioxide = {'carbon-dioxide', 10}
items.inputs.syngas = {'syngas', 10}
items.inputs.fluegas = {'flue-gas', 100}
items.inputs.fertilizer = {'fertilizer', 1}
items.inputs.ash = {'ash', 10}
items.inputs.limestone = {'limestone', 1}
items.inputs.stone = {'stone', 1}
items.inputs.biomass = {'biomass', 1}
items.inputs.manure = {'manure', 1}
items.inputs.fungalsubstrate = {'fungal-substrate', 1}
items.inputs.fungalsubstrate02 = {'fungal-substrate-02', 1}
items.inputs.fungalsubstrate03 = {'fungal-substrate-03', 1}
items.inputs.nitrogen = {'nitrogen', 10}
items.inputs.smalllamp = {'small-lamp', 1}
items.inputs.slackedlime = {'slacked-lime', 10}
items.inputs.watersaline = {'water-saline', 10}
items.inputs.irondust = {'iron-ore-dust', 1}
items.inputs.sand = {'sand', 10}
items.inputs.clay = {'clay', 10}
items.inputs.waterbarrel = {'water-barrel', 1}
items.inputs.gh = {'gh', 1}
items.inputs.antiviral = {'antiviral', 1}
items.inputs.anabolicrna = {'anabolic-rna', 1}
items.inputs.ralesiaseeds = {'ralesia-seeds', 5}
items.inputs.thuupraseeds = {'thuupra-seeds', 5}
items.inputs.yotoiseeds = {'yotoi-seeds', 5}
items.inputs.renneaseeds = {'rennea-seeds', 5}
items.inputs.cagedulric = {'caged-ulric', 1}
items.inputs.cagedmukmoux = {'caged-mukmoux', 1}
items.inputs.cage = {'cage', 1}
items.inputs.ulricfood01 = {'ulric-food-01', 1}
items.inputs.ulricfood02 = {'ulric-food-02', 1}
items.inputs.mukmouxfood01 = {'mukmoux-food-01', 1}
items.inputs.mukmouxfood02 = {'mukmoux-food-02', 1}
items.inputs.mukmouxcalf = {'mukmoux-calf', 1}
items.inputs.ulriccub = {'ulric-cub', 1}
items.inputs.ralesias = {'ralesias', 1}
items.inputs.meat = {'meat',1}
items.inputs.bones = {'bones', 1}
items.inputs.blood = {'blood',10}
items.inputs.skin = {'skin', 1}
items.inputs.brain = {'brain',1}
items.inputs.guts = {'guts',1}
items.inputs.fat = {'mukmoux-fat',1}
items.inputs.bonemeal = {'bonemeal',1}
items.inputs.emptybarrel = {'empty-barrel',1}
items.inputs.salt = {'salt',1}
items.inputs.rawfiber = {'raw-fiber',1}
items.inputs.fawogaespore = {'fawogae-spore',1}
items.inputs.fawogae = {'fawogae',1}
items.inputs.navensspore = {'navens-spore',1}
items.inputs.navens = {'navens',1}
items.inputs.bhoddosspore = {'bhoddos-spore',1}
items.inputs.bhoddos = {'bhoddos',1}
items.inputs.urea = {'urea',1}
items.inputs.bacteria2 = {'bacteria-2',1} --pyht
items.inputs.yaedolsspore = {'yaedols-spores',1}
items.inputs.yaedols = {'yaedols',1}
items.inputs.wood = {'wood',1}
items.inputs.moss = {'moss',1}
items.inputs.ammonia = {'ammonia',2}
items.inputs.grod = {'grod',1}
items.inputs.grodseeds = {'grod-seeds',3}
items.inputs.bedding = {'bedding',1}
items.inputs.cagedphagnot = {'caged-phagnot', 1}
items.inputs.phagnotcub = {'phagnot-cub', 1}
items.inputs.gasbladder = {'gas-bladder', 1}
items.inputs.phagnotfood01 = {'phagnot-food-01', 1}
items.inputs.phagnotfood02 = {'phagnot-food-02', 1}

items.outputs = items.inputs
--can put output replacements below here

return items
