local items = {}
items.inputs = {}
items.outputs = {}
--table.itemkey = {item, default item amount}

items.inputs.water = {'water', 100}
items.inputs.soil = {'soil', 10}
items.inputs.saps = {'saps', 1}
items.inputs.hydrogen = {'hydrogen', 10}
items.inputs.coarse = {'coarse', 10}
items.inputs.carbondioxide = {'carbon-dioxide', 10}
items.inputs.syngas = {'syngas', 10}
items.inputs.fluegas = {'flue-gas', 100}
items.inputs.fertilizer = {'fertilizer', 1}
items.inputs.ash = {'ash', 10}
items.inputs.limestone = {'limestone', 1}
items.inputs.stone = {'stone', 1}
items.inputs.biomass = {'biomass', 1}
items.inputs.manure = {'manure', 1}
items.inputs.cocoon = {'cocoon', 1}
items.inputs.fungalsubstrate = {'fungal-substrate', 1}
items.inputs.fungalsubstrate02 = {'fungal-substrate-02', 1}
items.inputs.fungalsubstrate03 = {'fungal-substrate-03', 1}
items.inputs.nitrogen = {'nitrogen', 10}
items.inputs.oxygen = {'oxygen', 10}
items.inputs.smalllamp = {'small-lamp', 1}
items.inputs.slackedlime = {'slacked-lime', 10}
items.inputs.watersaline = {'water-saline', 10}
items.inputs.irondust = {'iron-ore-dust', 1}
items.inputs.sand = {'sand', 10}
items.inputs.lignin = {'lignin', 1}
items.inputs.clay = {'clay', 10}
items.inputs.waterbarrel = {'water-barrel', 1}
items.inputs.emptybarrelmilk = {'empty-barrel-milk', 1}
items.inputs.milkbarrel = {'barrel-milk', 1}
items.inputs.gh = {'gh', 1}
items.inputs.antiviral = {'antiviral', 1}
items.inputs.nanochondria = {'nanochondria', 1}
items.inputs.anabolicrna = {'anabolic-rna', 1}
items.inputs.bmp = {'bmp', 1}
items.inputs.pheromones = {'pheromones', 1}
items.inputs.antitumor = {'antitumor', 1}
items.inputs.recombinantery = {'recombinant-ery', 1}
items.inputs.reca = {'reca', 1}
items.inputs.orexigenic = {'orexigenic', 1}
items.inputs.ralesiaseeds = {'ralesia-seeds', 5}
items.inputs.thuupraseeds = {'thuupra-seeds', 5}
items.inputs.yotoiseeds = {'yotoi-seeds', 5}
items.inputs.yotoi = {'yotoi', 1}
items.inputs.yotoifruit = {'yotoi-fruit', 1}
items.inputs.bloodmeal = {'blood-meal', 1}
items.inputs.renneaseeds = {'rennea-seeds', 5}
items.inputs.rennea = {'rennea', 1}
items.inputs.cagedulric = {'caged-ulric', 1}
items.inputs.braincagedulric = {'brain-caged-ulric', 1}
items.inputs.bonecagedulric = {'bone-caged-ulric', 1}
items.inputs.meatcagedulric = {'meat-caged-ulric', 1}
items.inputs.bloodcagedulric = {'blood-caged-ulric', 1}
items.inputs.skincagedulric = {'skin-caged-ulric', 1}
items.inputs.gutscagedulric = {'guts-caged-ulric', 1}
items.inputs.fatcagedulric = {'fat-caged-ulric', 1}
items.inputs.cagedmukmoux = {'caged-mukmoux', 1}
items.inputs.braincagedmukmoux = {'brain-caged-mukmoux', 1}
items.inputs.bonecagedmukmoux = {'bone-caged-mukmoux', 1}
items.inputs.meatcagedmukmoux = {'meat-caged-mukmoux', 1}
items.inputs.bloodcagedmukmoux = {'blood-caged-mukmoux', 1}
items.inputs.skincagedmukmoux = {'skin-caged-mukmoux', 1}
items.inputs.gutscagedmukmoux = {'guts-caged-mukmoux', 1}
items.inputs.fatcagedmukmoux = {'fat-caged-mukmoux', 1}
items.inputs.cagedauog = {'caged-auog', 1}
items.inputs.auogpup = {'auog-pup', 1}
items.inputs.braincagedauog = {'brain-caged-auog', 1}
items.inputs.bonecagedauog = {'bone-caged-auog', 1}
items.inputs.meatcagedauog = {'meat-caged-auog', 1}
items.inputs.bloodcagedauog = {'blood-caged-auog', 1}
items.inputs.skincagedauog = {'skin-caged-auog', 1}
items.inputs.gutscagedauog = {'guts-caged-auog', 1}
items.inputs.fatcagedauog = {'fat-caged-auog', 1}
items.inputs.auogfood01 = {'auog-food-01', 1}
items.inputs.auogfood02 = {'auog-food-02', 1}
items.inputs.cagedarthurian = {'caged-arthurian', 1}
items.inputs.arthurianegg = {'arthurian-egg', 1}
items.inputs.braincagedarthurian = {'brain-caged-arthurian', 1}
items.inputs.bonecagedarthurian = {'bone-caged-arthurian', 1}
items.inputs.meatcagedarthurian = {'meat-caged-arthurian', 1}
items.inputs.bloodcagedarthurian = {'blood-caged-arthurian', 1}
items.inputs.skincagedarthurian = {'skin-caged-arthurian', 1}
items.inputs.gutscagedarthurian = {'guts-caged-arthurian', 1}
items.inputs.fatcagedarthurian = {'fat-caged-arthurian', 1}
items.inputs.dhilmos = {'dhilmos', 1}
items.inputs.dhilmosegg = {'dhilmos-egg', 1}
items.inputs.meatdhilmos = {'meat-dhilmos', 1}
items.inputs.blooddhilmos = {'blood-dhilmos', 1}
items.inputs.gutsdhilmos = {'guts-dhilmos', 1}
items.inputs.fatdhilmos = {'fat-dhilmos', 1}
items.inputs.dhilmosfood01 = {'dhilmos-food-01', 1}
items.inputs.dhilmosfood02 = {'dhilmos-food-02', 1}
items.inputs.arthurianfood01 = {'arthurian-food-01', 1}
items.inputs.arthurianfood02 = {'arthurian-food-02', 1}
items.inputs.cage = {'cage', 1}
items.inputs.filtrationmedia = {'filtration-media', 1}
items.inputs.ulricfood01 = {'ulric-food-01', 1}
items.inputs.ulricfood02 = {'ulric-food-02', 1}
items.inputs.mukmouxfood01 = {'mukmoux-food-01', 1}
items.inputs.mukmouxfood02 = {'mukmoux-food-02', 1}
items.inputs.mukmouxcalf = {'mukmoux-calf', 1}
items.inputs.ulriccub = {'ulric-cub', 1}
items.inputs.ralesias = {'ralesias', 1}
items.inputs.meat = {'meat',1}
items.inputs.bones = {'bones', 1}
items.inputs.blood = {'blood',10}
items.inputs.arthropodblood = {'arthropod-blood',1}
items.inputs.phytoplankton = {'phytoplankton',1}
items.inputs.watersaline = {'water-saline',1}
items.inputs.seaweed = {'seaweed',2}
items.inputs.skin = {'skin', 1}
items.inputs.brain = {'brain',1}
items.inputs.guts = {'guts',1}
items.inputs.fat = {'mukmoux-fat',1}
items.inputs.bonemeal = {'bonemeal',1}
items.inputs.emptybarrel = {'empty-barrel',1}
items.inputs.salt = {'salt',1}
items.inputs.rawfiber = {'raw-fiber',1}
items.inputs.fawogaespore = {'fawogae-spore',1}
items.inputs.fawogae = {'fawogae',1}
items.inputs.navensspore = {'navens-spore',1}
items.inputs.navens = {'navens',1}
items.inputs.bhoddosspore = {'bhoddos-spore',1}
items.inputs.bhoddos = {'bhoddos',1}
items.inputs.urea = {'urea',1}
items.inputs.bacteria2 = {'bacteria-2',1} --pyht
items.inputs.yaedolsspore = {'yaedols-spores',1}
items.inputs.yaedols = {'yaedols',1}
items.inputs.wood = {'wood',1}
items.inputs.woodseeds = {'wood-seeds',1}
items.inputs.moss = {'moss',1}
items.inputs.ammonia = {'ammonia',2}
items.inputs.grod = {'grod',1}
items.inputs.grodseeds = {'grod-seeds',3}
items.inputs.bedding = {'bedding',1}
items.inputs.cagedphagnot = {'caged-phagnot', 1}
items.inputs.phagnotcub = {'phagnot-cub', 1}
items.inputs.gasbladder = {'gas-bladder', 1}
items.inputs.chitin = {'chitin', 1}
items.inputs.phagnotfood01 = {'phagnot-food-01', 1}
items.inputs.phagnotfood02 = {'phagnot-food-02', 1}
items.inputs.braincagedphagnot = {'brain-caged-phagnot', 1}
items.inputs.bonecagedphagnot = {'bone-caged-phagnot', 1}
items.inputs.meatcagedphagnot = {'meat-caged-phagnot', 1}
items.inputs.bloodcagedphagnot = {'blood-caged-phagnot', 1}
items.inputs.skincagedphagnot = {'skin-caged-phagnot', 1}
items.inputs.gutscagedphagnot = {'guts-caged-phagnot', 1}
items.inputs.braincageddingrits = {'brain-caged-dingrits', 1}
items.inputs.bonecageddingrits = {'bone-caged-dingrits', 1}
items.inputs.meatcageddingrits = {'meat-caged-dingrits', 1}
items.inputs.bloodcageddingrits = {'blood-caged-dingrits', 1}
items.inputs.gutscageddingrits = {'guts-caged-dingrits', 1}
items.inputs.fatcageddingrits = {'fat-caged-dingrits', 1}
items.inputs.cageddingrits = {'caged-dingrits', 1}
items.inputs.dingritscub = {'dingrits-cub', 1}
items.inputs.cagedscondrix = {'caged-scrondrix', 1}
items.inputs.pelt = {'pelt', 1}
items.inputs.dingritspike = {'dingrit-spike', 1}
items.inputs.dingritsfood01 = {'dingrits-food-01', 1}
items.inputs.dingritsfood02 = {'dingrits-food-02', 1}
items.inputs.yotoileaves = {'yotoi-leaves', 1}
items.inputs.tuuphra = {'tuuphra', 1}
items.inputs.tuuphraseeds = {'tuuphra-seeds', 1}
items.inputs.meatcagedkmauts = {'meat-caged-kmauts', 1}
items.inputs.bloodcagedkmauts = {'blood-caged-kmauts', 1}
items.inputs.gutscagedkmauts = {'guts-caged-kmauts', 1}
items.inputs.fatcagedkmauts = {'fat-caged-kmauts', 1}
items.inputs.braincagedkmauts = {'brain-caged-kmauts', 1}
items.inputs.cagedkmauts = {'caged-kmauts', 1}
items.inputs.kmautscub = {'kmauts-cub', 1}
items.inputs.tendon = {'tendon', 1}
items.inputs.kmautsration = {'kmauts-ration', 1}
items.inputs.cridren = {'cridren', 1}
items.inputs.cridrenseeds = {'cridren-seeds', 1}
items.inputs.chalkysoil = {'chalky-soil', 1}
items.inputs.fish = {'fish', 1}
items.inputs.fishfood1 = {'fish-food-01', 1}
items.inputs.fishfood2 = {'fish-food-02', 1}
items.inputs.fishegg = {'fish-egg', 1}
items.inputs.sponge = {'sponge', 1}
items.inputs.fishoil = {'fish-oil', 1}
items.inputs.finenexelit = {'fine-nexelit-powder', 1}

items.inputs.cagedscrondrix = {'caged-scrondrix', 1}
items.inputs.braincagedscrondrix = {'brain-caged-scrondrix', 1}
items.inputs.bonecagedscrondrix = {'bone-caged-scrondrix', 1}
items.inputs.meatcagedscrondrix = {'meat-caged-scrondrix', 1}
items.inputs.bloodcagedscrondrix = {'blood-caged-scrondrix', 1}
items.inputs.skincagedscrondrix = {'skin-caged-scrondrix', 1}
items.inputs.gutscagedscrondrix = {'guts-caged-scrondrix', 1}
items.inputs.fatcagedscrondrix = {'fat-caged-scrondrix', 1}
items.inputs.scrondrixcub = {'scrondrix-pup', 1}
items.inputs.pinealgland = {'pineal-gland', 1}

items.inputs.cagedphadai = {'caged-phadai', 1}
items.inputs.braincagedphadai = {'brain-caged-phadai', 1}
items.inputs.bonecagedphadai = {'bone-caged-phadai', 1}
items.inputs.meatcagedphadai = {'meat-caged-phadai', 1}
items.inputs.bloodcagedphadai = {'blood-caged-phadai', 1}
items.inputs.skincagedphadai = {'skin-caged-phadai', 1}
items.inputs.gutscagedphadai = {'guts-caged-phadai', 1}
items.inputs.fatcagedphadai = {'fat-caged-phadai', 1}
items.inputs.phadaipup = {'phadai-pup', 1}
items.inputs.carapace = {'carapace', 1}
items.inputs.energydrink = {'energy-drink', 1}
items.inputs.speaker = {'programmable-speaker', 1}
items.inputs.phadaifood01 = {'phadai-food-01', 1}
items.inputs.phadaifood02 = {'phadai-food-02', 1}

items.inputs.kicalk = {'kicalk', 1}
items.inputs.kicalkseeds = {'kicalk-seeds', 1}

items.inputs.cagedantelope = {'caged-antelope', 1}
items.inputs.antelopecage = {'cage-antelope', 1}
items.inputs.nanocellulose = {'nano-cellulose', 1}
items.inputs.strangelets = {'strangelets', 1}

items.inputs.cadavericarumseeds = {'cadaveric-arum-seeds', 1}
items.inputs.cadavericarum = {'cadaveric-arum', 1}
items.inputs.coalgas = {'coal-gas', 10}
items.inputs.stonewool = {'stone-wool', 1}
items.inputs.acidgas = {'acidgas', 10}

items.inputs.vonix = {'vonix', 1}
items.inputs.vonixegg = {'vonix-eggs', 1}
items.inputs.venongland = {'venon-gland', 1}
items.inputs.brainvonix = {'brain-vonix', 1}
items.inputs.meatvonix = {'meat-vonix', 1}
items.inputs.bloodvonix = {'blood-vonix', 1}
items.inputs.skinvonix = {'skin-vonix', 1}
items.inputs.gutsvonix = {'guts-vonix', 1}
items.inputs.fatvonix = {'fat-vonix', 1}

items.inputs.zipir = {'zipir1', 1}
items.inputs.zipiregg = {'zipir-eggs', 1}
items.inputs.brainzipir = {'brain-zipir', 1}
items.inputs.meatzipir = {'meat-zipir', 1}
items.inputs.bloodzipir = {'blood-zipir', 1}
items.inputs.skinzipir = {'skin-zipir', 1}
items.inputs.gutszipir = {'guts-zipir', 1}
items.inputs.fatzipir = {'fat-zipir', 1}
items.inputs.zipirfood01 = {'zipir-food-01', 1}
items.inputs.zipirfood02 = {'zipir-food-02', 1}
items.inputs.wastewater = {'waste-water', 10}
items.inputs.pressuredwater = {'pressured-water', 10}
items.inputs.fawogaesubstrate = {'fawogae-substrate', 1}

items.inputs.trits = {'trits', 1}
items.inputs.tritscub = {'trits-pup', 1}
items.inputs.braintrits = {'brain-trits', 1}
items.inputs.bonetrits = {'bone-trits', 1}
items.inputs.meattrits = {'meat-trits', 1}
items.inputs.bloodtrits = {'blood-trits', 1}
items.inputs.skintrits = {'skin-trits', 1}
items.inputs.gutstrits = {'guts-trits', 1}
items.inputs.fattrits = {'fat-trits', 1}
items.inputs.albumin = {'albumin', 1}
items.inputs.sodiumalginate = {'sodium-alginate', 1}

items.inputs.xeno = {'xeno', 1}
items.inputs.cagedxeno = {'caged-xeno', 1}
items.inputs.xenoegg = {'xeno-egg', 1}
items.inputs.brainxeno = {'brain-xeno', 1}
items.inputs.bonexeno = {'bone-xeno', 1}
items.inputs.meatxeno = {'meat-xeno', 1}
items.inputs.bloodxeno = {'sulfuric-xeno', 1}
items.inputs.chitinxeno = {'chitin-xeno', 1}
items.inputs.sulfuricacid = {'sulfuric-acid', 1}

items.inputs.cagedvrauks = {'caged-vrauks', 1}
items.inputs.braincagedvrauks = {'brain-caged-vrauks', 1}
items.inputs.meatcagedvrauks = {'meat-caged-vrauks', 1}
items.inputs.bloodcagedvrauks = {'blood-caged-vrauks', 1}
items.inputs.skincagedvrauks = {'chitin-caged-vrauks', 1}
items.inputs.gutscagedvrauks = {'guts-caged-vrauks', 1}
items.inputs.vrauksfood01 = {'vrauks-food-01', 1}
items.inputs.vrauksfood02 = {'vrauks-food-02', 1}
items.inputs.formicacid = {'formic-acid', 1}

items.inputs.meatxyhiphoe = {'meat-xyhiphoe', 1}
items.inputs.bloodxyhiphoe = {'blood-xyhiphoe', 1}
items.inputs.gutsxyhiphoe = {'guts-xyhiphoe', 1}
items.inputs.shellxyhiphoe = {'shell-xyhiphoe', 1}
items.inputs.xyhiphoecub = {'xyhiphoe-cub', 1}
items.inputs.shell = {'shell', 1}
items.inputs.xyhiphoe = {'xyhiphoe', 1}

items.inputs.milk = {'milk', 1}
items.inputs.cagedkorlex = {'caged-korlex', 1}
items.inputs.braincagedkorlex = {'brain-caged-korlex', 1}
items.inputs.meatcagedkorlex = {'meat-caged-korlex', 1}
items.inputs.bloodcagedkorlex = {'blood-caged-korlex', 1}
items.inputs.gutscagedkorlex = {'guts-caged-korlex', 1}
items.inputs.skincagedkorlex = {'skin-caged-korlex', 1}
items.inputs.bonecagedkorlex = {'bone-caged-korlex', 1}
items.inputs.fatcagedkorlex = {'fat-caged-korlex', 1}
items.inputs.korlexpup = {'korlex-pup', 1}
items.inputs.korlexfood01 = {'korlex-food-01', 1}
items.inputs.korlexfood02 = {'korlex-food-02', 1}


items.outputs = items.inputs
--can put output replacements below here

return items
