
local TRlist = {
    {tech = 'bigger-colon', oldrecipe = 'manure-1', newrecipe = 'manure-1a'},
    {tech = 'bigger-colon', oldrecipe = 'manure-2', newrecipe = 'manure-2a'},
    {tech = 'bigger-colon', oldrecipe = 'manure-3', newrecipe = 'manure-3a'},
    {tech = 'bigger-colon', oldrecipe = 'manure-4', newrecipe = 'manure-4a'},
    {tech = 'bigger-colon', oldrecipe = 'manure-5', newrecipe = 'manure-5a'},
    {tech = 'bigger-colon', oldrecipe = 'manure-6', newrecipe = 'manure-6a'},
    {tech = 'bigger-colon', oldrecipe = 'manure-7', newrecipe = 'manure-7a'},
    {tech = 'explosive-diarrhea', oldrecipe = 'manure-1a', newrecipe = 'manure-1b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'manure-2a', newrecipe = 'manure-2b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'manure-3a', newrecipe = 'manure-3b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'manure-4a', newrecipe = 'manure-4b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'manure-5a', newrecipe = 'manure-5b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'manure-6a', newrecipe = 'manure-6b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'manure-7a', newrecipe = 'manure-7b'},
    {tech = 'bigger-colon', oldrecipe = 'muk-manure-1', newrecipe = 'muk-manure-1a'},
    {tech = 'bigger-colon', oldrecipe = 'muk-manure-2', newrecipe = 'muk-manure-2a'},
    {tech = 'bigger-colon', oldrecipe = 'muk-manure-3', newrecipe = 'muk-manure-3a'},
    {tech = 'bigger-colon', oldrecipe = 'muk-manure-4', newrecipe = 'muk-manure-4a'},
    {tech = 'bigger-colon', oldrecipe = 'muk-manure-5', newrecipe = 'muk-manure-5a'},
    {tech = 'bigger-colon', oldrecipe = 'muk-manure-6', newrecipe = 'muk-manure-6a'},
    {tech = 'bigger-colon', oldrecipe = 'muk-manure-7', newrecipe = 'muk-manure-7a'},
    {tech = 'explosive-diarrhea', oldrecipe = 'muk-manure-1a', newrecipe = 'muk-manure-1b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'muk-manure-2a', newrecipe = 'muk-manure-2b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'muk-manure-3a', newrecipe = 'muk-manure-3b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'muk-manure-4a', newrecipe = 'muk-manure-4b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'muk-manure-5a', newrecipe = 'muk-manure-5b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'muk-manure-6a', newrecipe = 'muk-manure-6b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'muk-manure-7a', newrecipe = 'muk-manure-7b'},
    {tech = 'bigger-colon', oldrecipe = 'auog-manure-1', newrecipe = 'auog-manure-1a'},
    {tech = 'bigger-colon', oldrecipe = 'auog-manure-2', newrecipe = 'auog-manure-2a'},
    {tech = 'bigger-colon', oldrecipe = 'auog-manure-3', newrecipe = 'auog-manure-3a'},
    {tech = 'bigger-colon', oldrecipe = 'auog-manure-4', newrecipe = 'auog-manure-4a'},
    {tech = 'bigger-colon', oldrecipe = 'auog-manure-5', newrecipe = 'auog-manure-5a'},
    {tech = 'bigger-colon', oldrecipe = 'auog-manure-6', newrecipe = 'auog-manure-6a'},
    {tech = 'bigger-colon', oldrecipe = 'auog-manure-7', newrecipe = 'auog-manure-7a'},
    {tech = 'explosive-diarrhea', oldrecipe = 'auog-manure-1a', newrecipe = 'auog-manure-1b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'auog-manure-2a', newrecipe = 'auog-manure-2b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'auog-manure-3a', newrecipe = 'auog-manure-3b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'auog-manure-4a', newrecipe = 'auog-manure-4b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'auog-manure-5a', newrecipe = 'auog-manure-5b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'auog-manure-6a', newrecipe = 'auog-manure-6b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'auog-manure-7a', newrecipe = 'auog-manure-7b'},
    {tech = 'bigger-colon', oldrecipe = 'phag-manure-1', newrecipe = 'phag-manure-1a'},
    {tech = 'bigger-colon', oldrecipe = 'phag-manure-2', newrecipe = 'phag-manure-2a'},
    {tech = 'bigger-colon', oldrecipe = 'phag-manure-3', newrecipe = 'phag-manure-3a'},
    {tech = 'bigger-colon', oldrecipe = 'phag-manure-4', newrecipe = 'phag-manure-4a'},
    {tech = 'bigger-colon', oldrecipe = 'phag-manure-5', newrecipe = 'phag-manure-5a'},
    {tech = 'bigger-colon', oldrecipe = 'phag-manure-6', newrecipe = 'phag-manure-6a'},
    {tech = 'bigger-colon', oldrecipe = 'phag-manure-7', newrecipe = 'phag-manure-7a'},
    {tech = 'explosive-diarrhea', oldrecipe = 'phag-manure-1a', newrecipe = 'phag-manure-1b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'phag-manure-2a', newrecipe = 'phag-manure-2b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'phag-manure-3a', newrecipe = 'phag-manure-3b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'phag-manure-4a', newrecipe = 'phag-manure-4b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'phag-manure-5a', newrecipe = 'phag-manure-5b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'phag-manure-6a', newrecipe = 'phag-manure-6b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'phag-manure-7a', newrecipe = 'phag-manure-7b'},
    {tech = 'bigger-colon', oldrecipe = 'scrondrix-manure-1', newrecipe = 'scrondrix-manure-1a'},
    {tech = 'bigger-colon', oldrecipe = 'scrondrix-manure-2', newrecipe = 'scrondrix-manure-2a'},
    {tech = 'bigger-colon', oldrecipe = 'scrondrix-manure-3', newrecipe = 'scrondrix-manure-3a'},
    {tech = 'bigger-colon', oldrecipe = 'scrondrix-manure-4', newrecipe = 'scrondrix-manure-4a'},
    {tech = 'bigger-colon', oldrecipe = 'scrondrix-manure-5', newrecipe = 'scrondrix-manure-5a'},
    {tech = 'bigger-colon', oldrecipe = 'scrondrix-manure-6', newrecipe = 'scrondrix-manure-6a'},
    {tech = 'bigger-colon', oldrecipe = 'scrondrix-manure-7', newrecipe = 'scrondrix-manure-7a'},
    {tech = 'explosive-diarrhea', oldrecipe = 'scrondrix-manure-1a', newrecipe = 'scrondrix-manure-1b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'scrondrix-manure-2a', newrecipe = 'scrondrix-manure-2b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'scrondrix-manure-3a', newrecipe = 'scrondrix-manure-3b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'scrondrix-manure-4a', newrecipe = 'scrondrix-manure-4b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'scrondrix-manure-5a', newrecipe = 'scrondrix-manure-5b'},
    {tech = 'explosive-diarrhea', oldrecipe = 'scrondrix-manure-6a', newrecipe = 'scrondrix-manure-6b'},
--brains 1--
    {tech = 'interactive-cognition', oldrecipe = 'Full Render arthurians', newrecipe = 'Full Render arthuriansb'},
    {tech = 'interactive-cognition', oldrecipe = 'Extract arthurian brains', newrecipe = 'Extract arthurian brainsb'},
    {tech = 'interactive-cognition', oldrecipe = 'Full Render auogs', newrecipe = 'Full Render auogsb'},
    {tech = 'interactive-cognition', oldrecipe = 'Extract auog brains', newrecipe = 'Extract auog brainsb'},
    {tech = 'interactive-cognition', oldrecipe = 'Full Render dingrits', newrecipe = 'Full Render dingritsb'},
    {tech = 'interactive-cognition', oldrecipe = 'Extract dingrits brains', newrecipe = 'Extract dingrits brainsb'},
    {tech = 'interactive-cognition', oldrecipe = 'Full Render kmauts', newrecipe = 'Full Render kmautsb'},
    {tech = 'interactive-cognition', oldrecipe = 'Extract kmauts brains', newrecipe = 'Extract kmauts brainsb'},
    {tech = 'interactive-cognition', oldrecipe = 'Full Render Mukmouxs', newrecipe = 'Full Render Mukmouxsb'},
    {tech = 'interactive-cognition', oldrecipe = 'Extract Mukmoux brains', newrecipe = 'Extract Mukmoux brainsb'},
    {tech = 'interactive-cognition', oldrecipe = 'Full Render phadais', newrecipe = 'Full Render phadaisb'},
    {tech = 'interactive-cognition', oldrecipe = 'Extract phadai brains', newrecipe = 'Extract phadai brainsb'},
    {tech = 'interactive-cognition', oldrecipe = 'Full Render phagnots', newrecipe = 'Full Render phagnotsb'},
    {tech = 'interactive-cognition', oldrecipe = 'Extract phagnot brains', newrecipe = 'Extract phagnot brainsb'},
    {tech = 'interactive-cognition', oldrecipe = 'Full Render scrondrixs', newrecipe = 'Full Render scrondrixsb'},
    {tech = 'interactive-cognition', oldrecipe = 'Extract scrondrix brains', newrecipe = 'Extract scrondrix brainsb'},
    {tech = 'interactive-cognition', oldrecipe = 'Full Render Trits', newrecipe = 'Full Render Tritsb'},
    {tech = 'interactive-cognition', oldrecipe = 'Extract Trits brains', newrecipe = 'Extract Trits brainsb'},
    {tech = 'interactive-cognition', oldrecipe = 'Full Render Ulrics', newrecipe = 'Full Render Ulricsb'},
    {tech = 'interactive-cognition', oldrecipe = 'Extract Ulric brains', newrecipe = 'Extract Ulric brainsb'},
    {tech = 'interactive-cognition', oldrecipe = 'Full Render Vonix', newrecipe = 'Full Render Vonixb'},
    {tech = 'interactive-cognition', oldrecipe = 'Extract Vonix brain', newrecipe = 'Extract Vonix brainb'},
    {tech = 'interactive-cognition', oldrecipe = 'Full Render Vrauks', newrecipe = 'Full Render Vrauksb'},
    {tech = 'interactive-cognition', oldrecipe = 'Extract Vrauks brains', newrecipe = 'Extract Vrauks brainsb'},
    {tech = 'interactive-cognition', oldrecipe = 'Full Render Xenos', newrecipe = 'Full Render Xenosb'},
    {tech = 'interactive-cognition', oldrecipe = 'Extract Xeno brains', newrecipe = 'Extract Xeno brainsb'},
    {tech = 'interactive-cognition', oldrecipe = 'Full Render zipir', newrecipe = 'Full Render zipirb'},
    {tech = 'interactive-cognition', oldrecipe = 'Extract zipir brain', newrecipe = 'Extract zipir brainb'},
--brains 2--
    {tech = 'metamide5', oldrecipe = 'Extract arthurian brainsb', newrecipe = 'Extract arthurian brains-2'},
    {tech = 'metamide5', oldrecipe = 'Extract brains from Improved arthurians', newrecipe = 'Extract brains from Improved arthurians-2'},
    {tech = 'metamide5', oldrecipe = 'Extract auog brainsb', newrecipe = 'Extract auog brains-2'},
    {tech = 'metamide5', oldrecipe = 'Extract brains from Improved auogs', newrecipe = 'Extract brains from Improved auogs-2'},
    {tech = 'metamide5', oldrecipe = 'Extract dingrits brainsb', newrecipe = 'Extract dingrits brains-2'},
    {tech = 'metamide5', oldrecipe = 'Extract brains from Improved dingrits', newrecipe = 'Extract brains from Improved dingrits-2'},
    {tech = 'metamide5', oldrecipe = 'Extract kmauts brainsb', newrecipe = 'Extract kmauts brains-2'},
    {tech = 'metamide5', oldrecipe = 'Extract brains from Improved kmauts', newrecipe = 'Extract brains from Improved kmauts-2'},
    {tech = 'metamide5', oldrecipe = 'Extract Mukmoux brainsb', newrecipe = 'Extract Mukmoux brains-2'},
    {tech = 'metamide5', oldrecipe = 'Extract brains from Improved Mukmouxs', newrecipe = 'Extract brains from Improved Mukmouxs-2'},
    {tech = 'metamide5', oldrecipe = 'Extract phadai brainsb', newrecipe = 'Extract phadai brains-2'},
    {tech = 'metamide5', oldrecipe = 'Extract brains from Improved phadais', newrecipe = 'Extract brains from Improved phadais-2'},
    {tech = 'metamide5', oldrecipe = 'Extract phagnot brainsb', newrecipe = 'Extract phagnot brains-2'},
    {tech = 'metamide5', oldrecipe = 'Extract brains from Improved phagnots', newrecipe = 'Extract brains from Improved phagnots-2'},
    {tech = 'metamide5', oldrecipe = 'Extract scrondrix brainsb', newrecipe = 'Extract scrondrix brains-2'},
    {tech = 'metamide5', oldrecipe = 'Extract brains from Improved scrondrixs', newrecipe = 'Extract brains from Improved scrondrixs-2'},
    {tech = 'metamide5', oldrecipe = 'Extract Trits brainsb', newrecipe = 'Extract Trits brains-2'},
    {tech = 'metamide5', oldrecipe = 'Extract brains from Improved Trits', newrecipe = 'Extract brains from Improved Trits-2'},
    {tech = 'metamide5', oldrecipe = 'Extract Ulric brainsb', newrecipe = 'Extract Ulric brains-2'},
    {tech = 'metamide5', oldrecipe = 'Extract brains from Improved Ulrics', newrecipe = 'Extract brains from Improved Ulrics-2'},
    {tech = 'metamide5', oldrecipe = 'Extract Vonix brainb', newrecipe = 'Extract Vonix brain-2'},
    {tech = 'metamide5', oldrecipe = 'Extract brains from Improved Vonixes', newrecipe = 'Extract brains from Improved Vonixes-2'},
    {tech = 'metamide5', oldrecipe = 'Extract Vrauks brainsb', newrecipe = 'Extract Vrauks brains-2'},
    {tech = 'metamide5', oldrecipe = 'Extract brains from Improved Vrauks', newrecipe = 'Extract brains from Improved Vrauks-2'},
    {tech = 'metamide5', oldrecipe = 'Extract Xeno brainsb', newrecipe = 'Extract Xeno brains-2'},
    {tech = 'metamide5', oldrecipe = 'Extract brains from Improved Xenos', newrecipe = 'Extract brains from Improved Xenos-2'},
    {tech = 'metamide5', oldrecipe = 'Extract zipir brainb', newrecipe = 'Extract zipir brain-2'},
    {tech = 'metamide5', oldrecipe = 'Extract brains from Improved Zipir', newrecipe = 'Extract brains from Improved Zipir-2'},
--meat 1--
    {tech = 'exercises', oldrecipe = 'Extract arthurian Meat', newrecipe = 'Extract arthurian Meat-1'},
    {tech = 'exercises', oldrecipe = 'Extract auog Meat', newrecipe = 'Extract auog Meat-1'},
    {tech = 'exercises', oldrecipe = 'Extract dhilmos Meat', newrecipe = 'Extract dhilmos Meat-1'},
    {tech = 'exercises', oldrecipe = 'Extract dingrits Meat', newrecipe = 'Extract dingrits Meat-1'},
    {tech = 'exercises', oldrecipe = 'Extract kmauts Meat', newrecipe = 'Extract kmauts Meat-1'},
    {tech = 'exercises', oldrecipe = 'Extract Mukmoux Meat', newrecipe = 'Extract Mukmoux Meat-1'},
    {tech = 'exercises', oldrecipe = 'Extract phadai Meat', newrecipe = 'Extract phadai Meat-1'},
    {tech = 'exercises', oldrecipe = 'Extract phagnot Meat', newrecipe = 'Extract phagnot Meat-1'},
    {tech = 'exercises', oldrecipe = 'Extract scrondrix Meat', newrecipe = 'Extract scrondrix Meat-1'},
    {tech = 'exercises', oldrecipe = 'Extract Trits Meat', newrecipe = 'Extract Trits Meat-1'},
    {tech = 'exercises', oldrecipe = 'Extract Ulric Meat', newrecipe = 'Extract Ulric Meat-1'},
    {tech = 'exercises', oldrecipe = 'Extract Vonix Meat', newrecipe = 'Extract Vonix Meat-1'},
    {tech = 'exercises', oldrecipe = 'Extract Vrauks Meat', newrecipe = 'Extract Vrauks Meat-1'},
    {tech = 'exercises', oldrecipe = 'Extract Xeno Meat', newrecipe = 'Extract Xeno Meat-1'},
    {tech = 'exercises', oldrecipe = 'Extract xyhiphoe Meat', newrecipe = 'Extract xyhiphoe Meat-1'},
    {tech = 'exercises', oldrecipe = 'Extract zipir Meat', newrecipe = 'Extract zipir Meat-1'},
--meat 2--
    {tech = 'myostatin', oldrecipe = 'Extract arthurian Meat-1', newrecipe = 'Extract arthurian Meat-2'},
    {tech = 'myostatin', oldrecipe = 'Extract auog Meat-1', newrecipe = 'Extract auog Meat-2'},
    {tech = 'myostatin', oldrecipe = 'Extract meat from Improved arthurians', newrecipe = 'Extract meat from Improved arthurians-2'},
    {tech = 'myostatin', oldrecipe = 'Extract meat from Improved auogs', newrecipe = 'Extract meat from Improved auogs-2'},
    {tech = 'myostatin', oldrecipe = 'Extract dhilmos Meat-1', newrecipe = 'Extract dhilmos Meat-2'},
    {tech = 'myostatin', oldrecipe = 'Extract meat from Improved dhilmoss', newrecipe = 'Extract meat from Improved dhilmoss-2'},
    {tech = 'myostatin', oldrecipe = 'Extract dingrits Meat-1', newrecipe = 'Extract dingrits Meat-2'},
    {tech = 'myostatin', oldrecipe = 'Extract meat from Improved dingrits', newrecipe = 'Extract meat from Improved dingrits-2'},
    {tech = 'myostatin', oldrecipe = 'Extract kmauts Meat-1', newrecipe = 'Extract kmauts Meat-2'},
    {tech = 'myostatin', oldrecipe = 'Extract meat from Improved kmauts', newrecipe = 'Extract meat from Improved kmauts-2'},
    {tech = 'myostatin', oldrecipe = 'Extract Mukmoux Meat-1', newrecipe = 'Extract Mukmoux Meat-2'},
    {tech = 'myostatin', oldrecipe = 'Extract meat from Improved Mukmouxs', newrecipe = 'Extract meat from Improved Mukmouxs-2'},
    {tech = 'myostatin', oldrecipe = 'Extract phadai Meat-1', newrecipe = 'Extract phadai Meat-2'},
    {tech = 'myostatin', oldrecipe = 'Extract meat from Improved phadais', newrecipe = 'Extract meat from Improved phadais-2'},
    {tech = 'myostatin', oldrecipe = 'Extract phagnot Meat-1', newrecipe = 'Extract phagnot Meat-2'},
    {tech = 'myostatin', oldrecipe = 'Extract meat from Improved phagnots', newrecipe = 'Extract meat from Improved phagnots-2'},
    {tech = 'myostatin', oldrecipe = 'Extract scrondrix Meat-1', newrecipe = 'Extract scrondrix Meat-2'},
    {tech = 'myostatin', oldrecipe = 'Extract meat from Improved scrondrixs', newrecipe = 'Extract meat from Improved scrondrixs-2'},
    {tech = 'myostatin', oldrecipe = 'Extract Trits Meat-1', newrecipe = 'Extract Trits Meat-2'},
    {tech = 'myostatin', oldrecipe = 'Extract meat from Improved Trits', newrecipe = 'Extract meat from Improved Trits-2'},
    {tech = 'myostatin', oldrecipe = 'Extract Ulric Meat-1', newrecipe = 'Extract Ulric Meat-2'},
    {tech = 'myostatin', oldrecipe = 'Extract meat from Improved Ulrics', newrecipe = 'Extract meat from Improved Ulrics-2'},
    {tech = 'myostatin', oldrecipe = 'Extract Vonix Meat-1', newrecipe = 'Extract Vonix Meat-2'},
    {tech = 'myostatin', oldrecipe = 'Extract meat from Improved Vonixes', newrecipe = 'Extract meat from Improved Vonixes-2'},
    {tech = 'myostatin', oldrecipe = 'Extract Vrauks Meat-1', newrecipe = 'Extract Vrauks Meat-2'},
    {tech = 'myostatin', oldrecipe = 'Extract meat from Improved Vrauks', newrecipe = 'Extract meat from Improved Vrauks-2'},
    {tech = 'myostatin', oldrecipe = 'Extract Xeno Meat-1', newrecipe = 'Extract Xeno Meat-2'},
    {tech = 'myostatin', oldrecipe = 'Extract meat from Improved Xenos', newrecipe = 'Extract meat from Improved Xenos-2'},
    {tech = 'myostatin', oldrecipe = 'Extract xyhiphoe Meat-1', newrecipe = 'Extract xyhiphoe Meat-2'},
    {tech = 'myostatin', oldrecipe = 'Extract meat from Improved xyhiphoe', newrecipe = 'Extract meat from Improved xyhiphoe-2'},
    {tech = 'myostatin', oldrecipe = 'Extract zipir Meat-1', newrecipe = 'Extract zipir Meat-2'},
    {tech = 'myostatin', oldrecipe = 'Extract meat from Improved Zipir', newrecipe = 'Extract meat from Improved Zipir-2'},

--bone 1--
    {tech = 'osteocyte', oldrecipe = 'Extract arthurian bones', newrecipe = 'Extract arthurian bones-1'},
    {tech = 'osteocyte', oldrecipe = 'Extract auog bones', newrecipe = 'Extract auog bones-1'},
    {tech = 'osteocyte', oldrecipe = 'Extract dingrits bones', newrecipe = 'Extract dingrits bones-1'},
    {tech = 'osteocyte', oldrecipe = 'Extract Mukmoux bones', newrecipe = 'Extract Mukmoux bones-1'},
    {tech = 'osteocyte', oldrecipe = 'Extract phadai bones', newrecipe = 'Extract phadai bones-1'},
    {tech = 'osteocyte', oldrecipe = 'Extract phagnot bones', newrecipe = 'Extract phagnot bones-1'},
    {tech = 'osteocyte', oldrecipe = 'Extract scrondrix bones', newrecipe = 'Extract scrondrix bones-1'},
    {tech = 'osteocyte', oldrecipe = 'Extract Trits bones', newrecipe = 'Extract Trits bones-1'},
    {tech = 'osteocyte', oldrecipe = 'Extract Ulric bones', newrecipe = 'Extract Ulric bones-1'},
    {tech = 'osteocyte', oldrecipe = 'Extract Xeno bones', newrecipe = 'Extract Xeno bones-1'},

--bone 2--
    {tech = 'hardened-bone', oldrecipe = 'Extract arthurian bones-1', newrecipe = 'Extract arthurian bones-2'},
    {tech = 'hardened-bone', oldrecipe = 'Extract bones from Improved arthurians', newrecipe = 'Extract bones from Improved arthurians-2'},
    {tech = 'hardened-bone', oldrecipe = 'Extract auog bones-1', newrecipe = 'Extract auog bones-2'},
    {tech = 'hardened-bone', oldrecipe = 'Extract bones from Improved auogs', newrecipe = 'Extract bones from Improved auogs-2'},
    {tech = 'hardened-bone', oldrecipe = 'Extract dingrits bones-1', newrecipe = 'Extract dingrits bones-2'},
    {tech = 'hardened-bone', oldrecipe = 'Extract bones from Improved dingrits', newrecipe = 'Extract bones from Improved dingrits-2'},
    {tech = 'hardened-bone', oldrecipe = 'Extract Mukmoux bones-1', newrecipe = 'Extract Mukmoux bones-2'},
    {tech = 'hardened-bone', oldrecipe = 'Extract bones from Improved Mukmouxs', newrecipe = 'Extract bones from Improved Mukmouxs-2'},
    {tech = 'hardened-bone', oldrecipe = 'Extract phadai bones-1', newrecipe = 'Extract phadai bones-2'},
    {tech = 'hardened-bone', oldrecipe = 'Extract bones from Improved phadais', newrecipe = 'Extract bones from Improved phadais-2'},
    {tech = 'hardened-bone', oldrecipe = 'Extract phagnot bones-1', newrecipe = 'Extract phagnot bones-2'},
    {tech = 'hardened-bone', oldrecipe = 'Extract bones from Improved phagnots', newrecipe = 'Extract bones from Improved phagnots-2'},
    {tech = 'hardened-bone', oldrecipe = 'Extract scrondrix bones-1', newrecipe = 'Extract scrondrix bones-2'},
    {tech = 'hardened-bone', oldrecipe = 'Extract bones from Improved scrondrixs', newrecipe = 'Extract bones from Improved scrondrixs-2'},
    {tech = 'hardened-bone', oldrecipe = 'Extract Trits bones-1', newrecipe = 'Extract Trits bones-2'},
    {tech = 'hardened-bone', oldrecipe = 'Extract bones from Improved Trits', newrecipe = 'Extract bones from Improved Trits-2'},
    {tech = 'hardened-bone', oldrecipe = 'Extract Ulric bones-1', newrecipe = 'Extract Ulric bones-2'},
    {tech = 'hardened-bone', oldrecipe = 'Extract bones from Improved Ulrics', newrecipe = 'Extract bones from Improved Ulrics-2'},
    {tech = 'hardened-bone', oldrecipe = 'Extract Xeno bones-1', newrecipe = 'Extract Xeno bones-2'},
    {tech = 'hardened-bone', oldrecipe = 'Extract bones from Improved xenos', newrecipe = 'Extract bones from Improved xenos-2'},

--guts 1--
    {tech = 'organ-replication', oldrecipe = 'Extract arthurian guts', newrecipe = 'Extract arthurian guts-1'},
    {tech = 'organ-replication', oldrecipe = 'Extract auog guts', newrecipe = 'Extract auog guts-1'},
    {tech = 'organ-replication', oldrecipe = 'Extract dhilmos guts', newrecipe = 'Extract dhilmos guts-1'},
    {tech = 'organ-replication', oldrecipe = 'Extract dingrits guts', newrecipe = 'Extract dingrits guts-1'},
    {tech = 'organ-replication', oldrecipe = 'Extract kmauts guts', newrecipe = 'Extract kmauts guts-1'},
    {tech = 'organ-replication', oldrecipe = 'Extract Mukmoux guts', newrecipe = 'Extract Mukmoux guts-1'},
    {tech = 'organ-replication', oldrecipe = 'Extract phadai guts', newrecipe = 'Extract phadai guts-1'},
    {tech = 'organ-replication', oldrecipe = 'Extract phagnot guts', newrecipe = 'Extract phagnot guts-1'},
    {tech = 'organ-replication', oldrecipe = 'Extract scrondrix guts', newrecipe = 'Extract scrondrix guts-1'},
    {tech = 'organ-replication', oldrecipe = 'Extract Trits guts', newrecipe = 'Extract Trits guts-1'},
    {tech = 'organ-replication', oldrecipe = 'Extract Ulric guts', newrecipe = 'Extract Ulric guts-1'},
    {tech = 'organ-replication', oldrecipe = 'Extract Vonix guts', newrecipe = 'Extract Vonix guts-1'},
    {tech = 'organ-replication', oldrecipe = 'Extract Vrauks guts', newrecipe = 'Extract Vrauks guts-1'},
    {tech = 'organ-replication', oldrecipe = 'Extract xyhiphoe guts', newrecipe = 'Extract xyhiphoe guts-1'},
    {tech = 'organ-replication', oldrecipe = 'Extract zipir guts', newrecipe = 'Extract zipir guts-1'},

--guts 2--
    {tech = 'cavity', oldrecipe = 'Extract arthurian guts-1', newrecipe = 'Extract arthurian guts-2'},
    {tech = 'cavity', oldrecipe = 'Extract guts from Improved arthurians', newrecipe = 'Extract guts from Improved arthurians-2'},
    {tech = 'cavity', oldrecipe = 'Extract auog guts-1', newrecipe = 'Extract auog guts-2'},
    {tech = 'cavity', oldrecipe = 'Extract guts from Improved auogs', newrecipe = 'Extract guts from Improved auogs-2'},
    {tech = 'cavity', oldrecipe = 'Extract dhilmos guts-1', newrecipe = 'Extract dhilmos guts-2'},
    {tech = 'cavity', oldrecipe = 'Extract guts from Improved dhilmoss', newrecipe = 'Extract guts from Improved dhilmoss-2'},
    {tech = 'cavity', oldrecipe = 'Extract dingrits guts-1', newrecipe = 'Extract dingrits guts-2'},
    {tech = 'cavity', oldrecipe = 'Extract guts from Improved dingrits', newrecipe = 'Extract guts from Improved dingrits-2'},
    {tech = 'cavity', oldrecipe = 'Extract kmauts guts-1', newrecipe = 'Extract kmauts guts-2'},
    {tech = 'cavity', oldrecipe = 'Extract guts from Improved kmauts', newrecipe = 'Extract guts from Improved kmauts-2'},
    {tech = 'cavity', oldrecipe = 'Extract Mukmoux guts-1', newrecipe = 'Extract Mukmoux guts-2'},
    {tech = 'cavity', oldrecipe = 'Extract guts from Improved Mukmouxs', newrecipe = 'Extract guts from Improved Mukmouxs-2'},
    {tech = 'cavity', oldrecipe = 'Extract phadai guts-1', newrecipe = 'Extract phadai guts-2'},
    {tech = 'cavity', oldrecipe = 'Extract guts from Improved phadais', newrecipe = 'Extract guts from Improved phadais-2'},
    {tech = 'cavity', oldrecipe = 'Extract phagnot guts-1', newrecipe = 'Extract phagnot guts-2'},
    {tech = 'cavity', oldrecipe = 'Extract guts from Improved phagnots', newrecipe = 'Extract guts from Improved phagnots-2'},
    {tech = 'cavity', oldrecipe = 'Extract scrondrix guts-1', newrecipe = 'Extract scrondrix guts-2'},
    {tech = 'cavity', oldrecipe = 'Extract guts from Improved scrondrixs', newrecipe = 'Extract guts from Improved scrondrixs-2'},
    {tech = 'cavity', oldrecipe = 'Extract Trits guts-1', newrecipe = 'Extract Trits guts-2'},
    {tech = 'cavity', oldrecipe = 'Extract guts from Improved Trits', newrecipe = 'Extract guts from Improved Trits-2'},
    {tech = 'cavity', oldrecipe = 'Extract Ulric guts-1', newrecipe = 'Extract Ulric guts-2'},
    {tech = 'cavity', oldrecipe = 'Extract guts from Improved Ulrics', newrecipe = 'Extract guts from Improved Ulrics-2'},
    {tech = 'cavity', oldrecipe = 'Extract Vonix guts-1', newrecipe = 'Extract Vonix guts-2'},
    {tech = 'cavity', oldrecipe = 'Extract guts from Improved Vonixes', newrecipe = 'Extract guts from Improved Vonixes-2'},
    {tech = 'cavity', oldrecipe = 'Extract Vrauks guts-1', newrecipe = 'Extract Vrauks guts-2'},
    {tech = 'cavity', oldrecipe = 'Extract guts from Improved Ulrics', newrecipe = 'Extract guts from Improved Ulrics-2'},
    {tech = 'cavity', oldrecipe = 'Extract xyhiphoe guts-1', newrecipe = 'Extract xyhiphoe guts-2'},
    {tech = 'cavity', oldrecipe = 'Extract guts from Improved xyhiphoe', newrecipe = 'Extract guts from Improved xyhiphoe-2'},
    {tech = 'cavity', oldrecipe = 'Extract zipir guts-1', newrecipe = 'Extract zipir guts-2'},
    {tech = 'cavity', oldrecipe = 'Extract guts from Improved Zipir', newrecipe = 'Extract guts from Improved Zipir-2'},

--blood 1--
    {tech = 'somatic', oldrecipe = 'Extract arthurian blood', newrecipe = 'Extract arthurian blood-1'},
    {tech = 'somatic', oldrecipe = 'Extract auog blood', newrecipe = 'Extract auog blood-1'},
    {tech = 'somatic', oldrecipe = 'Extract dhilmos blood', newrecipe = 'Extract dhilmos blood-1'},
    {tech = 'somatic', oldrecipe = 'Extract dingrits blood', newrecipe = 'Extract dingrits blood-1'},
    {tech = 'somatic', oldrecipe = 'Extract kmauts blood', newrecipe = 'Extract kmauts blood-1'},
    {tech = 'somatic', oldrecipe = 'Extract Mukmoux blood', newrecipe = 'Extract Mukmoux blood-1'},
    {tech = 'somatic', oldrecipe = 'Extract phadai blood', newrecipe = 'Extract phadai blood-1'},
    {tech = 'somatic', oldrecipe = 'Extract phagnot blood', newrecipe = 'Extract phagnot blood-1'},
    {tech = 'somatic', oldrecipe = 'Extract scrondrix blood', newrecipe = 'Extract scrondrix blood-1'},
    {tech = 'somatic', oldrecipe = 'Extract Trits blood', newrecipe = 'Extract Trits blood-1'},
    {tech = 'somatic', oldrecipe = 'Extract Ulric blood', newrecipe = 'Extract Ulric blood-1'},
    {tech = 'somatic', oldrecipe = 'Extract Vonix blood', newrecipe = 'Extract Vonix blood-1'},
--    {tech = 'somatic', oldrecipe = 'Extract Vrauks blood', newrecipe = 'Extract Vrauks blood-1'},
    {tech = 'somatic', oldrecipe = 'Extract Xeno blood', newrecipe = 'Extract Xeno blood-1'},
    {tech = 'somatic', oldrecipe = 'Extract xyhiphoe blood', newrecipe = 'Extract xyhiphoe blood-1'},
    {tech = 'somatic', oldrecipe = 'Extract zipir blood', newrecipe = 'Extract zipir blood-1'},

--blood 2--
    {tech = 'transgenes', oldrecipe = 'Extract arthurian blood-1', newrecipe = 'Extract arthurian blood-2'},
    {tech = 'transgenes', oldrecipe = 'Extract blood from Improved arthurians', newrecipe = 'Extract blood from Improved arthurians-2'},
    {tech = 'transgenes', oldrecipe = 'Extract auog blood-1', newrecipe = 'Extract auog blood-2'},
    {tech = 'transgenes', oldrecipe = 'Extract blood from Improved auogs', newrecipe = 'Extract blood from Improved auogs-2'},
    {tech = 'transgenes', oldrecipe = 'Extract dhilmos blood-1', newrecipe = 'Extract dhilmos blood-2'},
    {tech = 'transgenes', oldrecipe = 'Extract blood from Improved dhilmoss', newrecipe = 'Extract blood from Improved dhilmoss-2'},
    {tech = 'transgenes', oldrecipe = 'Extract dingrits blood-1', newrecipe = 'Extract dingrits blood-2'},
    {tech = 'transgenes', oldrecipe = 'Extract blood from Improved dingrits', newrecipe = 'Extract blood from Improved dingrits-2'},
    {tech = 'transgenes', oldrecipe = 'Extract kmauts blood-1', newrecipe = 'Extract kmauts blood-2'},
    {tech = 'transgenes', oldrecipe = 'Extract blood from Improved kmauts', newrecipe = 'Extract blood from Improved kmauts-2'},
    {tech = 'transgenes', oldrecipe = 'Extract Mukmoux blood-1', newrecipe = 'Extract Mukmoux blood-2'},
    {tech = 'transgenes', oldrecipe = 'Extract blood from Improved Mukmouxs', newrecipe = 'Extract blood from Improved Mukmouxs-2'},
    {tech = 'transgenes', oldrecipe = 'Extract phadai blood-1', newrecipe = 'Extract phadai blood-2'},
    {tech = 'transgenes', oldrecipe = 'Extract blood from Improved phadais', newrecipe = 'Extract blood from Improved phadais-2'},
    {tech = 'transgenes', oldrecipe = 'Extract phagnot blood-1', newrecipe = 'Extract phagnot blood-2'},
    {tech = 'transgenes', oldrecipe = 'Extract blood from Improved phagnots', newrecipe = 'Extract blood from Improved phagnots-2'},
    {tech = 'transgenes', oldrecipe = 'Extract scrondrix blood-1', newrecipe = 'Extract scrondrix blood-2'},
    {tech = 'transgenes', oldrecipe = 'Extract blood from Improved scrondrixs', newrecipe = 'Extract blood from Improved scrondrixs-2'},
    {tech = 'transgenes', oldrecipe = 'Extract Trits blood-1', newrecipe = 'Extract Trits blood-2'},
    {tech = 'transgenes', oldrecipe = 'Extract blood from Improved Trits', newrecipe = 'Extract blood from Improved Trits-2'},
    {tech = 'transgenes', oldrecipe = 'Extract Ulric blood-1', newrecipe = 'Extract Ulric blood-2'},
    {tech = 'transgenes', oldrecipe = 'Extract blood from Improved Ulrics', newrecipe = 'Extract blood from Improved Ulrics-2'},
--    {tech = 'transgenes', oldrecipe = 'Extract Vrauks blood-1', newrecipe = 'Extract Vrauks blood-2'},
--    {tech = 'transgenes', oldrecipe = 'Extract blood from Improved Vrauks', newrecipe = 'Extract blood from Improved Vrauks-2'},
    {tech = 'transgenes', oldrecipe = 'Extract Xeno blood-1', newrecipe = 'Extract Xeno blood-2'},
    {tech = 'transgenes', oldrecipe = 'Extract blood from Improved Xenos', newrecipe = 'Extract blood from Improved Xenos-2'},
    {tech = 'transgenes', oldrecipe = 'Extract xyhiphoe blood-1', newrecipe = 'Extract xyhiphoe blood-2'},
    {tech = 'transgenes', oldrecipe = 'Extract blood from Improved xyhiphoe', newrecipe = 'Extract blood from Improved xyhiphoe-2'},
    {tech = 'transgenes', oldrecipe = 'Extract zipir blood-1', newrecipe = 'Extract zipir blood-2'},
    {tech = 'transgenes', oldrecipe = 'Extract Arthropod blood from Improved Zipir', newrecipe = 'Extract Arthropod blood from Improved Zipir-2'},

--skin 1--
    {tech = 'defective-collagen', oldrecipe = 'Extract arthurian skin', newrecipe = 'Extract arthurian skin-1'},
    {tech = 'defective-collagen', oldrecipe = 'Extract auog skin', newrecipe = 'Extract auog skin-1'},
    {tech = 'defective-collagen', oldrecipe = 'Extract dhilmos chitin', newrecipe = 'Extract dhilmos chitin-1'},
    {tech = 'defective-collagen', oldrecipe = 'Extract Mukmoux skin', newrecipe = 'Extract Mukmoux skin-1'},
    {tech = 'defective-collagen', oldrecipe = 'Extract phadai Skin', newrecipe = 'Extract phadai Skin-1'},
    {tech = 'defective-collagen', oldrecipe = 'Extract phagnot skin', newrecipe = 'Extract phagnot skin-1'},
    {tech = 'defective-collagen', oldrecipe = 'Extract scrondrix skin', newrecipe = 'Extract scrondrix skin-1'},
    {tech = 'defective-collagen', oldrecipe = 'Extract Trits skin', newrecipe = 'Extract Trits skin-1'},
    {tech = 'defective-collagen', oldrecipe = 'Extract Ulric skin', newrecipe = 'Extract Ulric skin-1'},
    {tech = 'defective-collagen', oldrecipe = 'Extract Vonix skin', newrecipe = 'Extract Vonix skin-1'},
    {tech = 'defective-collagen', oldrecipe = 'Extract Vrauks chithin', newrecipe = 'Extract Vrauks chithin-1'},
    {tech = 'defective-collagen', oldrecipe = 'Extract xeno chitin', newrecipe = 'Extract xeno chitin-1'},
    {tech = 'defective-collagen', oldrecipe = 'Extract zipir skin', newrecipe = 'Extract zipir skin-1'},

--skin 2--
    {tech = 'double-skin', oldrecipe = 'Extract arthurian skin-1', newrecipe = 'Extract arthurian skin-2'},
    {tech = 'double-skin', oldrecipe = 'Extract skin from Improved arthurians', newrecipe = 'Extract skin from Improved arthurians-2'},
    {tech = 'double-skin', oldrecipe = 'Extract auog skin-1', newrecipe = 'Extract auog skin-2'},
    {tech = 'double-skin', oldrecipe = 'Extract skin from Improved auogs', newrecipe = 'Extract skin from Improved auogs-2'},
    {tech = 'double-skin', oldrecipe = 'Extract dhilmos chitin-1', newrecipe = 'Extract dhilmos chitin-2'},
    {tech = 'double-skin', oldrecipe = 'Extract Mukmoux skin-1', newrecipe = 'Extract Mukmoux skin-2'},
    {tech = 'double-skin', oldrecipe = 'Extract skin from Improved Mukmouxs', newrecipe = 'Extract skin from Improved Mukmouxs-2'},
    {tech = 'double-skin', oldrecipe = 'Extract phadai Skin-1', newrecipe = 'Extract phadai Skin-2'},
    {tech = 'double-skin', oldrecipe = 'Extract skin from Improved phadais', newrecipe = 'Extract skin from Improved phadais-2'},
    {tech = 'double-skin', oldrecipe = 'Extract phagnot skin-1', newrecipe = 'Extract phagnot skin-2'},
    {tech = 'double-skin', oldrecipe = 'Extract skin from Improved phagnots', newrecipe = 'Extract skin from Improved phagnots-2'},
    {tech = 'double-skin', oldrecipe = 'Extract scrondrix skin-1', newrecipe = 'Extract scrondrix skin-2'},
    {tech = 'double-skin', oldrecipe = 'Extract skin from Improved scrondrixs', newrecipe = 'Extract skin from Improved scrondrixs-2'},
    {tech = 'double-skin', oldrecipe = 'Extract Trits skin-1', newrecipe = 'Extract Trits skin-2'},
    {tech = 'double-skin', oldrecipe = 'Extract skin from Improved Trits', newrecipe = 'Extract skin from Improved Trits-2'},
    {tech = 'double-skin', oldrecipe = 'Extract Ulric skin-1', newrecipe = 'Extract Ulric skin-2'},
    {tech = 'double-skin', oldrecipe = 'Extract skin from Improved Ulrics', newrecipe = 'Extract skin from Improved Ulrics-2'},
    {tech = 'double-skin', oldrecipe = 'Extract Vonix skin-1', newrecipe = 'Extract Vonix skin-2'},
    {tech = 'double-skin', oldrecipe = 'Extract skin from Improved Vonixes', newrecipe = 'Extract skin from Improved Vonixes-2'},
    {tech = 'double-skin', oldrecipe = 'Extract Vrauks chithin-1', newrecipe = 'Extract Vrauks chithin-2'},
    {tech = 'double-skin', oldrecipe = 'Extract skin from Improved Vrauks', newrecipe = 'Extract skin from Improved Vrauks-2'},
    {tech = 'double-skin', oldrecipe = 'Extract zipir skin-1', newrecipe = 'Extract zipir skin-2'},
    {tech = 'double-skin', oldrecipe = 'Extract skin from Improved Zipir', newrecipe = 'Extract skin from Improved Zipir-2'},
    
--fat 1--
    {tech = 'force-feeding', oldrecipe = 'Extract arthurian lard', newrecipe = 'Extract arthurian lard-1'},
    {tech = 'force-feeding', oldrecipe = 'Extract auog lard', newrecipe = 'Extract auog lard-1'},
    {tech = 'force-feeding', oldrecipe = 'Extract dhilmos lard', newrecipe = 'Extract dhilmos lard-1'},
    {tech = 'force-feeding', oldrecipe = 'Extract kmauts lard', newrecipe = 'Extract kmauts lard-1'},
    {tech = 'force-feeding', oldrecipe = 'Extract Mukmoux lard', newrecipe = 'Extract Mukmoux lard-1'},
    {tech = 'force-feeding', oldrecipe = 'Extract phadai Fat', newrecipe = 'Extract phadai Fat-1'},
    {tech = 'force-feeding', oldrecipe = 'Extract scrondrix lard', newrecipe = 'Extract scrondrix lard-1'},
    {tech = 'force-feeding', oldrecipe = 'Extract Trits lard', newrecipe = 'Extract Trits lard-1'},
    {tech = 'force-feeding', oldrecipe = 'Extract Vonix lard', newrecipe = 'Extract Vonix lard-1'},
    {tech = 'force-feeding', oldrecipe = 'Extract zipir lard', newrecipe = 'Extract zipir lard-1'},
 
--fat 2--
    {tech = 'fto4', oldrecipe = 'Extract arthurian lard-1', newrecipe = 'Extract arthurian lard-2'},
    {tech = 'fto4', oldrecipe = 'Extract fat from Improved arthurians', newrecipe = 'Extract fat from Improved arthurians-2'},
    {tech = 'fto4', oldrecipe = 'Extract auog lard-1', newrecipe = 'Extract auog lard-2'},
    {tech = 'fto4', oldrecipe = 'Extract fat from Improved auogs', newrecipe = 'Extract fat from Improved auogs-2'},
    {tech = 'fto4', oldrecipe = 'Extract dhilmos lard-1', newrecipe = 'Extract dhilmos lard-2'},
    {tech = 'fto4', oldrecipe = 'Extract fat from Improved dhilmoss', newrecipe = 'Extract fat from Improved dhilmoss-2'},
    {tech = 'fto4', oldrecipe = 'Extract kmauts lard-1', newrecipe = 'Extract kmauts lard-2'},
    {tech = 'fto4', oldrecipe = 'Extract fat from Improved kmauts', newrecipe = 'Extract fat from Improved kmauts-2'},
    {tech = 'fto4', oldrecipe = 'Extract Mukmoux lard-1', newrecipe = 'Extract Mukmoux lard-2'},
    {tech = 'fto4', oldrecipe = 'Extract fat from Improved Mukmouxs', newrecipe = 'Extract fat from Improved Mukmouxs-2'},
    {tech = 'fto4', oldrecipe = 'Extract phadai Fat-1', newrecipe = 'Extract phadai Fat-2'},
    {tech = 'fto4', oldrecipe = 'Extract fat from Improved phadais', newrecipe = 'Extract fat from Improved phadais-2'},
    {tech = 'fto4', oldrecipe = 'Extract scrondrix lard-1', newrecipe = 'Extract scrondrix lard-2'},
    {tech = 'fto4', oldrecipe = 'Extract fat from Improved scrondrixs', newrecipe = 'Extract fat from Improved scrondrixs-2'},
    {tech = 'fto4', oldrecipe = 'Extract Trits lard-1', newrecipe = 'Extract Trits lard-2'},
    {tech = 'fto4', oldrecipe = 'Extract fat from Improved Trits', newrecipe = 'Extract fat from Improved Trits-2'},
    {tech = 'fto4', oldrecipe = 'Extract Vonix lard-1', newrecipe = 'Extract Vonix lard-2'},
    {tech = 'fto4', oldrecipe = 'Extract fat from Improved Vonixes', newrecipe = 'Extract fat from Improved Vonixes-2'},
    {tech = 'fto4', oldrecipe = 'Extract zipir lard-1', newrecipe = 'Extract zipir lard-2'},
    {tech = 'fto4', oldrecipe = 'Extract fat from Improved Zipir', newrecipe = 'Extract fat from Improved Zipir-2'},

--bladder--
    {tech = 'bladder', oldrecipe = 'Extract phagnot Gas bladder', newrecipe = 'Extract phagnot Gas bladder-1'},

--formic--
    {tech = 'formic', oldrecipe = 'Extract Vrauks Formic Acid', newrecipe = 'Extract Vrauks Formic Acid-1'},

--carapace--
    {tech = 'party-animal', oldrecipe = 'Extract phadai Carapace', newrecipe = 'Extract phadai Carapace-1'},

--pelt--
    {tech = 'exo-insertion', oldrecipe = 'Extract dingrits Pelt', newrecipe = 'Extract dingrits Pelt-1'},

--spikes--
    {tech = 'argumented-spikes', oldrecipe = 'Extract dingrits Spikes', newrecipe = 'Extract dingrits Spikes-1'},

--pineal--
    {tech = 'conarium-stem', oldrecipe = 'Extract scrondrix Pineal Gland', newrecipe = 'Extract scrondrix Pineal Gland-1'},

--tendon--
    {tech = 'hydrolase-amplification', oldrecipe = 'Extract kmauts tendons', newrecipe = 'Extract kmauts tendons-1'},

--venom--
    {tech = 'zootoxins', oldrecipe = 'Extract Vonix´s Venom Gland', newrecipe = 'Extract Vonix´s Venom Gland-1'},

--shell--
    {tech = 'artificial-calcification', oldrecipe = 'Extract xyhiphoe shell', newrecipe = 'Extract xyhiphoe shell-1'},

--cortex--
    {tech = 'stochastic-cortex', oldrecipe = 'adrenal-cortex', newrecipe = 'adrenal-cortex-2'},

}


local technames = {}

for t,tech in pairs(data.raw.technology) do
	--log(serpent.block(tech))
	if tech.effects ~= nil then
	--log('hit')
		for e,effect in pairs(tech.effects) do
			--log('hit')
			if effect.type == 'unlock-recipe' then
				--log('hit')
				for u, unlock in pairs(TRlist) do
					--log('hit')
					if effect.recipe == unlock.oldrecipe then
						--log('hit')
						if technames[tech.name] == nil then
						table.insert(technames, tech.name)
						end
					end
				end
			end
		end
	end
end

log(serpent.block(technames))